### ISSUE TITLE
Full Camera Control

### ISSUE THREAD

**Issue by logibilo** [SteffeyDev/atemOSC#107]
Hi all,
I was wondering if it would be possible to get OSC control on settings of the "Camera" tab in the ATEM Software Control, such as Zoom, Focus, Aperture of cameras. Maybe also Lift, Gamma & Gain ?
Thx !

**Comment by logibilo** [comment]
Same solution than the topic about Hyperdeck control (https://github.com/danielbuechele/atemOSC/issues/102) : I found a workaround with Macros, AtemOsc is definitly a must have !

**Comment by SteffeyDev** [comment]
Merging #157 into here, basically want to support all features that [this board](https://www.blackmagicdesign.com/products/atemcameracontrolpanel) supports

**Comment by SteffeyDev** [comment]
Note to self: protocol details are in this doc:
https://documents.blackmagicdesign.com/UserManuals/BlackmagicPocketCinemaCameraManual.pdf?_v=1613635212000
Starting on page 163

**Comment by SteffeyDev** [comment]
Unfortunately, I'm going to have to delay this feature, as it uses a custom protocol for implementation and is very different from other control surfaces in the SDK.  As such, I will need a switcher and a camera to test with before I am able to develop this feature, as this sort of development requires a good amount of trial and error.  I should be able to get my hands on a camera and switcher at some point in the next few months, but no promises on when I will be able to get this done.

**Comment by nick-shaw** [comment]
If it's useful to anybody, I have put my own simple camera control app on [my GitHub](https://github.com/nick-shaw/ATEM-camera-control). Sadly no hardware support, as my coding skills are not up to that! Anybody feels like trying to add OSC or Midi support, go for it.

**Comment by nick-shaw** [comment]
There is now a [branch](https://github.com/nick-shaw/ATEM-camera-control/tree/mikmidi) of my app which does have (crude) MIDI support. It's very much hard-coded to my own setup, so anybody with a different setup would need to tweak the code and rebuild. But it's there for anybody who's interested.

**Comment by BuissonNeth** [comment]
Hello all,
Thank you for the development so far, very useful !
Will this feature be back on the menu ? With Elgato's Streamdeck+, this feature would be a big hit for a lot of us :)
I have daily access to ATEM 2 M/E and URSA cameras and can help you with some testing, do not hesitate.

Thank you !

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com/support would make it a higher priority for me.
