### ISSUE TITLE
M/E 2 control

### ISSUE THREAD

**Issue by blarkman** [SteffeyDev/atemOSC#11]
Hi all,
This program is amazing. Using it with QLab to program switcher changes during live broadcasts of events. Would be great if we could select M/E2 sources in the same way we can select M/E1 sources.  Maybe this is already possible, and I just don't know the syntax. Please let me know.

Thanks again to everyone who has contributed to this!

**Comment by SteffeyDev** [comment]
@blarkman if you are still using this setup, what commands don’t work on the M/E 2 that you think should?

**Comment by jeffadavisaz** [comment]
I have this same question. I'm doing the same exact setup actually. There are not addresses designated to send a command to the M/E2  side of the switcher, only M/E 1.

Thoughts?

**Comment by sneat** [comment]
There's actually quite a significant re-write that would be needed to support the M/E2 side so it's not a quick win unfortunately.

**Comment by jeffadavisaz** [comment]
Ahhhh Gotcha. I suppose I can write macros for what I need on the M/E 2 and trigger those instead.

**Comment by sneat** [comment]
@jeffadavisaz yeh, that's what I've been doing when I've needed. Generally it's been things like "set M/E2 program to X and then put M/E 2 'live'". So macros work well enough for that.

It'd be good to add full support at some point, it's just a pretty large body of work.

**Comment by HNTVideo** [comment]
Hi there! I am a big fan of the application! We use it all the time with our professional video setups for theatre performances so first off all, keep up the good work! :)

I was wondering, not being a programmer myself, if it is at all possible to control the M/E 2 part of the ATEM with the SDK. I was reading through the SDK and could not find it.

Thanks in advance!

**Comment by sneat** [comment]
@HNTVideo yes, it's technically possible to implement, but will involve a significant rewrite of the code to support it so it hasn't been started yet.

What I have done when I've wanted to control the M/E 2 component is to use macros. So setup macros via the official software control panel to control whatever functionality I'm needing, and then use atemOSC to trigger the macros. It's a bit tedious to setup, but still allows for a level of automation.

**Comment by SteffeyDev** [comment]
What would it actually take to support M/E 2 @sneat? I don't know the hardware, what makes those switchers so different?

**Comment by sneat** [comment]
An ATEM with M/E 2 is effectively 2 ATEM's in one, where you can then take the output of the 2nd M/E block as input into the first (main one).

We'd need to track both MixEffectBlocks (https://github.com/danielbuechele/atemOSC/blob/master/atemOSC/AppDelegate.mm#L308-L323) and update the OSC command paths to be able to support whether you're operating on the main M/E block or the 2nd one.

**Comment by SteffeyDev** [comment]
Completed in latest release, 4.0.0. See documentation for usage.
