### ISSUE TITLE
TSL 5.0 for tally control (and UMDs on multiviewer)

### ISSUE THREAD

**Issue by TVPROD** [SteffeyDev/atemOSC#112]
Hi Guys,
Do you know if there is a way to connect (via OSC) an external system (monitors, multiviewers...) to our ATEM universe ? I would love to implement TSL 5.0 but I don't know yet this protocol...

Thanks,
William

**Comment by SteffeyDev** [comment]
Not sure where you get TLS 5.0 from, current TLS version is 1.3, and even that is not widely supported yet. If you just want a remote connection, I see no reason why you can’t run atemOSC over a VPN, which will be very secure by default as long as you keep it up to date.  Are you familiar with VPN an networking topics?

**Comment by TVPROD** [comment]
Hi Peter,

No no :) I really wanted to speak about TSL protocols 3.1 (or 5.0), implemented in some equipment we have for UMDs :)

Thank you,
William

(depuis un terminal mobile)
William Japhet
william@tvprod.fr
06 80 12 89 17
