### ISSUE TITLE
Feedback LEDs on MIDI-controller

### ISSUE THREAD

**Issue by danielbuechele** [SteffeyDev/atemOSC#13]
I received this bug report via mail:

I recently bought the ICON iStage Controller (http://www.icon-global.com/Keyboards%2FPads_Pads_iStage.htm) and operate it in the DJ Mode as it enables me not only to send MIDI Notes to Osculator but also send MIDI Notes back to the controller to make the LEDs light blue or red. When a NOTE ON with velocity 127 is sent to the controller, the LED lights red, and with NOTE ON with velocity 0, the LED lights blue. That is great, I do not need to alter the data sent back from the ATEM to visualize the state of Program and Preview. What seems strange to me is the behavior of the MediaPlayer 1/2 Program Status (the IDs are 3010 and 3020). AtemOSC receives switching commands to /atem/program/3010, but it will not send back an OSC Call on /atem/program/3010 when switching occurs. I have to simulate the correct behavior in Osculator to show the corresponding LEDs light up.
Because I don't have any experiences in Xcode Programming, I don't know how I can do this on my own. I would also really like to include more feedback from the mixer (e.g. USK State, DSK State etc.)

**Comment by jcspencer** [comment]
This would be very useful. A query system would be great in AtemOSC

**Comment by beethovenjr** [comment]
This is a very useful... I use a BCF2000 and everything works great.. but the feedback of mp1 and mp2 DSK e USK dont work for me... 
Another problem is the feedback with a motorized fader on t-bar ... with i move the t-bar the feedback locks de fader...

**Comment by SteffeyDev** [comment]
@danielbuechele What's the status of this issue?

**Comment by carbon43** [comment]
Huh, this would be pretty interesting for me too, being able to accurately convey state without having to write my own external logic.
