### ISSUE TITLE
Recording control

### ISSUE THREAD

**Issue by juliafrey** [SteffeyDev/atemOSC#132]
Are there atem osc addresses to capture video? Record and stop?

**Comment by SteffeyDev** [comment]
Do you mean using hyperdeck?

**Comment by SteffeyDev** [comment]
In 2.5.7 I added some hyper deck commands such as `/atem/hyperdeck/<hyperdeck-id>/record` and `/atem/hyperdeck/<hyperdeck-id>/stop`.  The full list is available from the in-app list.

**Comment by juliafrey** [comment]
We aren't using hyperdecks, just capture through the atem software.

**Comment by SteffeyDev** [comment]
Ah, no that is not included yet. I’ll tag this as a feature request.

**Comment by SteffeyDev** [comment]
[Blackmagic Switchers SDK.pdf](https://github.com/danielbuechele/atemOSC/files/4081131/Blackmagic.Switchers.SDK.pdf)

@juliafrey I looked briefly, and couldn't find any way to capture video in the switcher manual.  I've attached the manual, if you can find a function we can call in the manual to control the video, I will happily add to this project.  Unfortunately, this app can only do what BlackMagic allows us to do.  Let me know if you find anything.

**Comment by randallpacker** [comment]
@SteffeyDev Peter, I just looked at the documentation and on page 570 I see the Record function (as well as play, stop, etc...) . I have included a screenshot. 
![Screenshot 2020-01-18 14 02 57](https://user-images.githubusercontent.com/3989315/72669066-7d4d1680-39fb-11ea-9b28-10fde273e7e7.jpg)

**Comment by SteffeyDev** [comment]
@randallpacker thats for hyperdeck, OP is asking for non-hyperdeck.

**Comment by randallpacker** [comment]
Thanks Peter for clarification.

**Comment by SteffeyDev** [comment]
It looks like they added support for this in the SDK over the past year! the latest 8.5 manual has a new section for recording to external devices.  So, I'll look into implementing this in the near future.

**Comment by rockgod407** [comment]
Hey! 

On top of this, I was wondering if it is at all possible to add in the ability to send a string to Name the file being recorded on the ATEM Pro // Pro ISO's. 

The macros in the ATEM Software Control don't allow us to create a macro to change the filename currently and would love to be able to automate my recording process by having cue lists from QLAB that name my recordings for me. 


<img width="419" alt="Screen Shot 2021-03-05 at 5 20 53 PM" src="https://user-images.githubusercontent.com/802315/110180081-24933580-7dd7-11eb-995b-0eaa5baefddd.png">

Maybe in section 12 of the new 8.6 SDK? 

[Blackmagic Switchers SDK.pdf](https://github.com/SteffeyDev/atemOSC/files/6093767/Blackmagic.Switchers.SDK.pdf)

<img width="827" alt="Section12" src="https://user-images.githubusercontent.com/802315/110180539-fbbf7000-7dd7-11eb-8b5c-cdc56e3fb2d5.png">

**Comment by SteffeyDev** [comment]
Funny you should mention that, I was working on this feature this week and went ahead and added support for setting file name because I anticipated the request. Hoping to get this released this weekend!

**Comment by rockgod407** [comment]
That would be phenomenal!! I have a week of virtual talent show recordings starting Monday that I would absolutely die to use this feature on. I just spent the past few hours trying to use AppleScript to automate the process and it's certainly very clunky. Can't wait to see what you have in store for us!!

**Comment by SteffeyDev** [comment]
Added in v4.1.0, just released.  Didn't have the ability to test this feature, so not sure if it works.  Give it a test and let me know!

**Comment by rockgod407** [comment]
Awesome, Just tested but got this error "Recording not available" 
<img width="1647" alt="Screen Shot 2021-03-05 at 10 15 39 PM" src="https://user-images.githubusercontent.com/802315/110193179-73a19080-7e00-11eb-9c3e-379f93e78741.png">

**Comment by SteffeyDev** [comment]
Can you turn on debug messages (button right), then disconnect and reconnect to switcher? Just want to confirm debug output is what I think it will be

**Comment by SteffeyDev** [comment]
Also, can you show me what ATEM software control shows for your drive?

**Comment by rockgod407** [comment]
Yep! here you go:
<img width="1650" alt="Screen Shot 2021-03-05 at 11 20 18 PM" src="https://user-images.githubusercontent.com/802315/110194948-5a511200-7e09-11eb-81f1-7bb8536aee86.png">

And then here's atem software control's panel for recording, and me manually hitting the record button to show that it will record to the drive from software control 
<img width="310" alt="Screen Shot 2021-03-05 at 11 17 43 PM" src="https://user-images.githubusercontent.com/802315/110194973-8371a280-7e09-11eb-88d2-a92ae2f149b2.png">
<img width="309" alt="Screen Shot 2021-03-05 at 11 17 34 PM" src="https://user-images.githubusercontent.com/802315/110194974-8371a280-7e09-11eb-826a-38a8c56ed82e.png">

**Comment by SteffeyDev** [comment]
Ok, are you running 8.6?  That error indicates that the SDK can't connect to the recording interface, which usually means that the switcher doesn't support it, which yours clearly does.

**Comment by SteffeyDev** [comment]
@randallpacker Do you have the ability to test this functionality out?

**Comment by randallpacker** [comment]
I just had a moment right now but I couldn't get the record function to work:

**Comment by randallpacker** [comment]
sorry, truncated message. Not quite sure how to construct the OSC message in VDMX. I used the same message: /atem/atem1/recording/start and got the same error message.

**Comment by SteffeyDev** [comment]
Ok, thanks for confirming

**Comment by SteffeyDev** [comment]
@petrihiissa I'm going to add an `/atem/recording/active` feedback message in the next release, which will include a single boolean value indicating when the recording is active.

**Comment by SteffeyDev** [comment]
Released in 4.2.0, let me know if you guys continue to have issues with this
