### ISSUE TITLE
With 2.54 Version: Or ATEM Software Control or AtemOsc Working

### ISSUE THREAD

**Issue by dadomultimedia** [SteffeyDev/atemOSC#140]
I´m using 2.54 version because 3.0 and 2.57 are crashing on Mojave.
I found this:
If I turn on AtemOSC first, the ATEM Software Control is not detecting the Atem MINI.
If I turn on ATEM Software Control First, the AtemOSC is not detecting either the Atem MINI.

I tried to set the IP Address in different ways:
- Giving the same IP address of the device in both software: 192.168.10.1
- Changing the last number for everyone: 192.168.10.2 and the other 192.168.10.3
- Changing just one of both and alternating that between both. (192.168.10.1 and the other 192.168.10.2)

Still trying to find a solution. Any help I will appreciate.
Thank you in advance.
David.

**Comment by SteffeyDev** [comment]
Have you tried 3.0.1?

**Comment by dadomultimedia** [comment]
Hi Daniel,
First of all, thank you a lot for your fast response. I truly cherish it.

Actually, After that I sent you the message, I downloaded 3.0.1, and the same, in this case, if I try to turn on the AtemOSC, without the ATEM Software Control, just get crash. I turn on first the ATEM Software Control and simply the AtemOSC, does not detect the device.
Right now, I was testing the 2.2 version. Just in case, but the same, like 2.54, detects the device but without the ATEM Software Control.
I could send you a couple of screenshots. or video shot if you like.

Greetings and Blessings.
David


________________________________
De: Peter Steffey <notifications@github.com>
Enviado: martes, 25 de febrero de 2020 05:29 a. m.
Para: danielbuechele/atemOSC <atemOSC@noreply.github.com>
CC: dadomultimedia <dadoproduccion@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [danielbuechele/atemOSC] With 2.54 Version: Or ATEM Software Control or AtemOsc Working (#140)


Have you tried 3.0.1?

**Comment by dadomultimedia** [comment]
Sorry, SteffeyDev.
These are the 2 screen-captures.

![ATEM Software Working But not AtemOSC](https://user-images.githubusercontent.com/19298145/75218180-1986dd80-575f-11ea-9d61-a4faa83ad057.png)
![AtemOSC Working but not ATEM Software Control](https://user-images.githubusercontent.com/19298145/75218182-1ab80a80-575f-11ea-8ab4-82a0f8a5d8eb.png)

**Comment by dadomultimedia** [comment]
By the way, these screens were made with 3.0.1 version

**Comment by SteffeyDev** [comment]
@dadomultimedia Can you try 3.0.5? I think I fixed most of the crashes

**Comment by dadomultimedia** [comment]
Oh great! I will, thank you! 
I will keep you informed. 
Greetings!

**Comment by alex519pgox** [comment]
Hi!
im on the 3.1.6, and i got exactly the same issue.
im running in mojave, the atem software control is on 8.2.3 and im using an atem mini.
the atem and the mac are connected to a switch that is connected to a router.
most of the time is my mistake on some bad connection or setting, there is some process i should check out?

cheers!
Alex

**Comment by alex519pgox** [comment]
Hi!

im sorry, i didn't change the settings or anything doing the same today and both programs works at the same time without problems.

sorry for the inconvenience.

**Comment by SteffeyDev** [comment]
Now that version 4 is out, I'm closing this. Open a new issue if problems persist.
