### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by gottesman** [SteffeyDev/atemOSC#141]
Hello Daniel. Your tool is sooooo useful. But i've encountered some troubles with production where me and my team only have 1 old mac wich we are wanting to get rid off because of its slowness, and we are using mainly Windows on production. So I was wondering if it is possible to port this tool in a way it can be multiplatform, like with C++ or something? I have little skills on programming but I know nothing about Objective-C and Mac stuff to try it myself. I now this is probably a difficult task and an egoist petition from my part, but I trully believe this will help more people out there. Thank you for your efforts and time.

(Sorry for my poor english, I hope it's easy to the eyes)

**Comment by SteffeyDev** [comment]
Hello, I am not Daniel but am the primary maintainer of the repository at this point.  I'm glad you are finding atemOSC useful!  I've considered porting to Windows for a number of years, as the church I volunteer for is actually in the same situation that you are in.

Our code is written in Objective-C++, so a lot of the code that interacts with the BlackMagic Switcher SDK could be reused with modifications.  The UI, of course, would need to be completely re-written.

Unfortunately, I only have time to maintain the current code base, and do not have time to spend the 20-30 or more hours needed to port to Windows.  I'm labeling this issue as help-wanted, and hope that someone else in the community will be able to take this on.  I would be happy to walk someone through the code and get them started as needed.

**Comment by sneat** [comment]
I'm a sometimes contributor to atemOSC and had previously created a program that did a similar role for Windows. You (both?) may find it useful, although I haven't updated it in a long time.

https://mcmillan.id.au/broadcast-controller/

Happy for this comment to be deleted if everyone wants, as it's promoting different software.

**Comment by SteffeyDev** [comment]
Ah interesting! That looks pretty handy actually, with just a few more basic ATEM features it could handle a majority of cases I think.  Macro support is nice so you could make it work for all features right now, which is cool.

**Comment by SteffeyDev** [comment]
I'll try it out, maybe we can add to the readme until someone has time to port this to Windows or you add equivalent functionality to broadcast control.

**Comment by sneat** [comment]
Yeh, I originally focussed on getting the macro support working, as that then allows you to do "the rest". I wrote it to mainly connect Atem with Xkeys

**Comment by gottesman** [comment]
Wow! Thank you very much for your time, Steffey.
And thank you too, Sneat. That program looks like something I could use, i will give it a try.

**Comment by mark-morreau** [comment]
Hi, I am just bumping this up, to ask again about the possibilities of porting AtemOSC to Windows, to see if anyone has time/inclination to do that. Unfortunately I don't know the first thing about programming, so I can't really try to do it myself. At least not without a lot of learning :-) 
I have used @sneat 's Broadcast Controller utility mentioned above, but, no offence Blair, I have not found it stable or reliable enough to trust in a live show environment.
Thank you!

**Comment by SteffeyDev** [comment]
Windows support is now possible since I've now switched to an Electron app in the [new version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). Is there anyone on this thread that would by an atemOSC license for a windows device?

**Comment by mark-morreau** [comment]
Hi, @SteffeyDev  I was delighted to see that you've now got the possibility of porting this to Windows. I would buy an atemOSC licence for a Windows device for sure.

**Comment by SteffeyDev** [comment]
@mark-morreau thanks for the response, in that case I'll see what I can get going! I'm hoping it's as simple as I think it will be.

**Comment by SteffeyDev** [comment]
Ok, atemOSC is officially available on Windows! And Linux as well, for completeness. You can download on www.atemosc.com.

**Comment by sneat** [comment]
Not a problem @mark-morreau - I actually assumed no one was using it. I hadn't updated it in years when I originally posted the message 3 years ago :)

Good job @SteffeyDev
