### ISSUE TITLE
Constant Status updates via OSC

### ISSUE THREAD

**Issue by RobLipop** [SteffeyDev/atemOSC#143]
I am SUPER new at this venture of OSC.  I read that your "module" provides full feedback.  Does this mean that i can constantly observe the status of the program bus?  

I am trying to put microphones on air that correspond to the camera that is on air.  I know that i can control my audio mixer with OSC -> MIDI.  But i am trying to figure out if i can start this sequence by being made aware every time a certain input is put on PGM.  

I think this is the exact use case of OSC.  but i need some help getting started.

**Comment by SteffeyDev** [comment]
When a module supports feedback, it means two things:
1) If the value is changed by another method (e.g. the ATEM Switcher Control software), an update is sent out over OSC with the new value
2) When you call /atem/send-status, it is sent out.

Not quite a continuous stream, but you could poll send-status as a regular interval.  Shouldn't be necessary though, as if you call send-status at the beginning, you will receive any later updates automatically if and when they occur.

**Comment by SteffeyDev** [comment]
Specifically, when a program is changed, an OSC message of `/atem/program` with a value of the program number as an `int` is sent out, and also the message `/atem/program/x`, where x is the program input number, so you can use either format.

**Comment by RobLipop** [comment]
Does an email post a response? 

I am trying to use tally data from an ATEM to control an X32 audio mixing console. I know that the x32 will take OSC commands (very well discussed on forums) and I have an upcoming need for this kind of integration. 

I have extensive experience with both the ATEM and the X32 but do not currently have access to either device. 

Are the emulators for either device? Would someone be interested in collaborating on a project? I can bring real world experiencing with using these products on high level shows. Hoping someone can bring the ability to build this integration. Oh, and I have a budget for this project as well. ;)

**Comment by SteffeyDev** [comment]
Ah I see, atemOSC will send feedback of `/atem/program/#` with the Input ID of the current camera every time it is changed, maybe you can use that?

**Comment by high-solutions** [comment]
With OSCulator you can have this up and running in 5 minutes. If you want i can make an example setup in OSCulator how to do this. The x32 has an on-pc version, you can even sync it with the hardware like the Atem software, the nice thing about the x32 software is that it always works, the Atem needs a device connected for the software to work i think.

**Comment by ruebyi** [comment]
> With OSCulator you can have this up and running in 5 minutes. If you want i can make an example setup in OSCulator how to do this. The x32 has an on-pc version, you can even sync it with the hardware like the Atem software, the nice thing about the x32 software is that it always works, the Atem needs a device connected for the software to work i think.

I would be very grateful for such an example setup...
