### ISSUE TITLE
Advanced Chroma Keying support

### ISSUE THREAD

**Issue by AndreasMUC** [SteffeyDev/atemOSC#149]
Please add support to control the Advanced Chroma Keyer. 
Using today's Chroma Key controls with a product which uses the advanced keyer crashed the app (e.g. Atem Mini).

IBMDSwitcherKeyAdvancedChromaParameters

**Comment by SteffeyDev** [comment]
We already support a number of advanced chroma key options.  If you had a crash, please attack the crash log to the issue.  If you would like additional parameters supported, please list which ones.

**Comment by AndreasMUC** [comment]
It seems that the current implementation is not compatible with the Atem Mini. Using any of them crashes the app.

Interesting parameters are:
ForegroundLevel
BackgroundLevel
KeyEdge
SpillSuppress
FlareSuppress

**Comment by SteffeyDev** [comment]
Have you tried the latest version 3.0.5?  You are correct, I don’t think those specific parameters are supported yet, so I’ll tag this as a feature request

**Comment by bqiu86** [comment]
> It seems that the current implementation is not compatible with the Atem Mini. Using any of them crashes the app.
> 
> Interesting parameters are:
> ForegroundLevel
> BackgroundLevel
> KeyEdge
> SpillSuppress
> FlareSuppress

These parameters are very useful. It would be great if you can add support!

**Comment by SteffeyDev** [comment]
Note to self: initial dev work complete, testing needed

**Comment by SteffeyDev** [comment]
I've released a [new major version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0) which includes support for these endpoints. Please test on that and open a support request at www.atemosc.com/support if there are any issues.
