### ISSUE TITLE
Could not get IBMDSwitcherInputSuperSource interface

### ISSUE THREAD

**Issue by johndores** [SteffeyDev/atemOSC#154]
Hello,

I m having trouble mapping a XTouch Mini using atemOSC and OSCulator.
atemOSC finds my atem, but I get this message in the end: Could not get IBMDSwitcherInputSuperSource interface. I also dont get a OSC Out IP Adress.
I am running ATEM Software Control ver. 8.2.1, and the ATEM is freshly updated(ATEM Television Studio HD).

What could be the problem? Pls help thx!

John

**Comment by SteffeyDev** [comment]
There is no problem, that is just a warning.  I'm assuming the XTouch Mini does not support super source.  The OSC Out IP Address is a value you need to enter, if you would like atemOSC to send feedback to an address. It is optional, however, if you don't want feedback.

**Comment by ruebyi** [comment]
I‘m running this exact combo and it‘s working perfectly!
