### ISSUE TITLE
add Flying Key controls

### ISSUE THREAD

**Issue by davvidavvi** [SteffeyDev/atemOSC#156]
ATEMs have a Flying Key option that let's you animate a PIP between 2 preset locations (keyframes) but the built in animations are linear and look painfully like something animated in PowerPoint V1. Any way to add those parameters to atemOSC (xPosition, yPosition, xSize, ySize) so moving them can be handled in a more fluid way through OSC (ex. with https://imimot.com/vezer/)

Thank you.

**Comment by high-solutions** [comment]
I vouch for this to, this really could create a load of options for qlab users with 1Dimension and 2Dimensions osc fades!!!

**Comment by davvidavvi** [comment]
Here's an example of how I'm currently using ATEM's built-in keyframes. The background is my computer screen, the foreground is an USK DVE of my camera, set to **Run To Full**. Then, **Run To B** slides it over to the left and masks it, and **Run To A** slides it off the screen. It's nice to be able to set up a scene and save the preset as a keyframe, but the hardware is only able to play it back with a linear animation. If those parameters are exposed through AtemOSC, then you could animate scenes with smoother animations, and with more than the 2 built-in keyframes (using any software that can send interpolated OSC values). 

[https://www.dropbox.com/s/qzh5cnf28b1ol21/AtemDVEKey.mov?dl=0](url)

**Comment by SteffeyDev** [comment]
Closing this in favor of #176, watch that issue for status
