### ISSUE TITLE
Camera Control

### ISSUE THREAD

**Issue by lifecenterericbradley** [SteffeyDev/atemOSC#157]
I'm new to this so I apologize if I am doing this wrong. I am looking for Camera control using a midi controller. If there is any solution for this, I would love to know, thank you!!

**Comment by carbon43** [comment]
Hey all good dude, this is totally possible. The missing link you're looking for, per se, is an app that can translate midi strings to other types of commands, like OSC strings. I personally use Octopus (https://www.octopusshowcontrol.com) in concert with atemOSC, and it works great. But I'll admit the learning curve can be a bit steep in terms of programming for someone new to this sort of thing. 

I'm not sure if @danielbuechele feels its kosher to link to other github projects (?) but Here To Record on youtube has done some great entry level tutorials for interfacing various devices and apps, and has made an app that has a maybe slightly lower learning curve for those just starting out. 

I am a terribly uninvolved ghost on Github, but the atemOSC group is pretty active and someone should come along to answer further questions in time :)

**Comment by SteffeyDev** [comment]
Unfortunately, the most camera control offered by atemOSC is just picking which camera is live (preview/program).  @lifecenterericbradley when you say camera control, what kind of aspects of the camera are you looking to control?

As @carbon43, you will need a third party app to translate Midi to OSC, then atemOSC can ingest that to control an ATEM switcher.  I've only used OSCulator, but I know there are a lot of options (such as Octopus mentioned above).

**Comment by HearNow** [comment]
@SteffeyDev I think I can answer this because I'm also looking for the same feature. The ATEM Software Control has an option for fine tuned camera control of multiple parameters like Gain, Color balance, white balance, etc. I'm trying to use a MIDI controller with CC data to manipulate some of these features.

**Comment by lifecenterericbradley** [comment]
Yes! That’s what I’m looking for. I’m looking for all the CCU control. Basically looking for a way to do most of this with midi  https://www.blackmagicdesign.com/products/atemcameracontrolpanel Instead of buying this hard panel or computer control. Would be open to any insights you have. I’ve also added my buddy Houston onto this thread. Thank you!!

Eric

**Comment by SteffeyDev** [comment]
OK, this is a good feature request and thus it will be tagged as such.  I don't have a ton of time to work on this but hoping to find other developers in this community that can contribute, preferably with actual access to hardware such as cameras.

**Comment by gride9000** [comment]
I want to second that this should be a priority for this project. The ability to control blackmagic pocket Cinema cameras is the reason I bought the atem mini pro. Being able to use the focus and zoom features with a midi fader would just be amazing.

**Comment by gride9000** [comment]
3rd, would use this feature right away

**Comment by SteffeyDev** [comment]
Just noticed I have two issues for camera control open, going to close this in favor of #107
