### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by SteffeyDev** [SteffeyDev/atemOSC#161]
Unfortunately, I have reached the stage in my life where, at least for the foreseeable future, I will no longer have much time, if any, to work on this project.  I also soon will no longer have access to a switcher for testing, and haven't had access to a newer switcher for some time.

Therefore, I am asking for other members of the community to step up and volunteer to maintain this project for the many users who depend on it.  It would be best if you (1) use atemOSC on a regular basis yourself, (2) you have access to one or more BlackMagic switchers (and ideally other products), and (3) a basic knowledge of programming.  You also must own a Mac to develop on.

If you are willing and able, I would be delighted to bring you up to speed on the code base via a conference call.  Feel free to reach out to me at steffeydev@icloud.com with any questions.

**Comment by carbon43** [comment]
Oh gosh 😮 

Just as a "throwing ideas out there" thing, have you considered reaching out to BMD to see if they'd consider taking over active development? I know many of us love and rely on this project. 

Also want to thank you for pouring so much work into this @SteffeyDev and wish you prosperity and happiness in your next chapter 💕

**Comment by danielbuechele** [comment]
Hey Peter, thank you so much for all the amazing work you put into maintaining and evolving this app.
Unfortunately, I currently don't have access to any BMD switcher, so it is hard for me to take over again. I will try to reach out to a few people and see if anyone is interested in taking leading this project.

All the best,
Daniel

**Comment by sneat** [comment]
I also no longer have access to any BMD switchers, so any dev work would be blind coding.

**Comment by danielbuechele** [comment]
If there is someone who has the capacity to carry on the project but lacking access to a switcher, we could try somehow finance an ATEM mini. Either through GitHub donations or some other sponsorships.

**Comment by high-solutions** [comment]
i have an atem mini and would love to have something to add to such an awesome project what has a lot of power. I just don't know where to start, not really a dev here :(

**Comment by SteffeyDev** [comment]
@high-solutions Can you send me an email at steffeydev@icloud.com so we can chat direct?

**Comment by bevanjkay** [comment]
@SteffeyDev I may be interested in helping where I can. I have access to a Production Studio 4k 2 M/E and an ATEM Mini Pro (remotely). However, my programming experience is more web / javascript based - willing to learn.

**Comment by SteffeyDev** [comment]
@bevanjkay I'm mainly a web developer as well, thankfully programming skills transfer well between languages.  Send me an email at steffeydev@icloud.com if you are still interesting in helping, and we can chat more there.

**Comment by iamjohnbarker** [comment]
Excellent work by all of the team over the years on this project! Really wish I had the time (and knowledge) to help keep it going for even longer but unfortunately I'm already struggling to keep up with projects. Either way, awesome work to all involved!

**Comment by MariusStuparu** [comment]
I also have an Atem Mini (and plan to keep it for some time), and am a full-stack developer (Swift knowledge included). I would love to be a part of this project.

**Comment by SteffeyDev** [comment]
@MariusStuparu Awesome! Send me an email at steffeydev@icloud.com and we'll chat :)

**Comment by SteffeyDev** [comment]
Ok, officially taking over this project again so going to close this issue
