### ISSUE TITLE
Stream Live endpoint & feedback

### ISSUE THREAD

**Issue by mkcologne** [SteffeyDev/atemOSC#162]
Is there a way to readout those values?

**Comment by SteffeyDev** [comment]
You can use `/atem/send-status` to get the values initially, then get updates automatically when they change, sent to the OSC out address.

**Comment by mkcologne** [comment]
I'm working on a full size TouchOSC Setup (will share it here, when done) … I trigger the Stream with Macros and it would be nice to have an "OnAir"-Sign on the iPad … like led/green and red, who say the mixer is online. But ist the Stream online? U know what I mean?

Cheers - Michael

**Comment by SteffeyDev** [comment]
Ah, the stream live is a new setting that is not yet addressed.  I will mark this as a feature request

**Comment by SteffeyDev** [comment]
The recording aspect is covered by #158, so this issue will be for stream only

**Comment by SteffeyDev** [comment]
Got it working for me on an ATEM Mini Pro ISO, so I'll ship this with the next release.

**Comment by randallpacker** [comment]
Thanks Peter! looking forward to the new release. I am wondering if you ever had a chance to look through the problem I was having with Hyperdeck "Timeline Time" in which the Hyperdeck is supposed to play through all clips. It was not working properly and would not play beyond the longest clip as I recall.

**Comment by SteffeyDev** [comment]
That is on my list, I should get to that later tonight or tomorrow.

**Comment by SteffeyDev** [comment]
Released in 4.2.0, feel free to re-open if you have any issues with this feature
