### ISSUE TITLE
Not able to Install atemOSC on my work computer because not issues by an Identified Developer

### ISSUE THREAD

**Issue by marsy62** [SteffeyDev/atemOSC#166]
Hi,

I am not able to Install atemOSC on my work computer because not issues by an Identified Developer.

At work, our administrators do not allow us to do us, by policy.

Is there a possibility that the software will be signed as such in the future ?

**Comment by marsy62** [comment]
Hi, 

How about making atemOSC an app with a "identified developer" ?

May I attach the error message (in French, but I can translate if needed) and the specs of my computer ?

Best regards.

Makha Sy

<img width="698" alt="Macbook Pro specs" src="https://user-images.githubusercontent.com/56013895/87148180-7661db00-c29d-11ea-8416-ffcd6c035516.png">

<img width="423" alt="Impossible to open the app_warning message" src="https://user-images.githubusercontent.com/56013895/87148135-5f22ed80-c29d-11ea-829e-943adbe4b4d3.png">

**Comment by SteffeyDev** [comment]
So looks like Apple has made stricter requirements for apps, we now need to sign and notarize both the app and the dmg.  I'll tackle that when I have the chance, but for the meantime added instructions on the README on how to bypass the warning.

**Comment by marsy62** [comment]
Thanks so much for simolving this issue with version 4.0 !
Congratulations !!

**Comment by SteffeyDev** [comment]
You're welcome, glad it works!
