### ISSUE TITLE
Trigger Upstream Keys on Atem ME2

### ISSUE THREAD

**Issue by midiwizard** [SteffeyDev/atemOSC#168]
Thanks for this great piece of software. I give you many thanks. 
Is there any way to trigger up stream keys on ME2 on an ATEM switcher?

**Comment by mkcologne** [comment]
Actually it's not direct possible. You can setup a workaround with Macros.
Have a look here: #167 
Perhaps that can help u.
Cheers - Michael

**Comment by randallpacker** [comment]
Thanks Michael. I have a copy of your TouchOSC template, fantastic work. I know I can create a macro for loop, but just wondering why it wasn't implemented along with play and stop. 

I am building an ATEM interface similar to yours in VDMX. 

Randall

**Comment by mkcologne** [comment]
Randall, sounds interesting. Will do some HD Functions in the next Version. 
Also do some experiments with Arena to combine the stuff. Especially for Visuals.
Please share it, when done!
Cheers - Michael

**Comment by SteffeyDev** [comment]
ME 2 support is close, keep an eye on #11 and look out for V4 release.

**Comment by SteffeyDev** [comment]
In case anyone missed it, v4.0.0 added support for ME2
