### ISSUE TITLE
Loop Control for Hyperdeck

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#169]
I just noticed that there is no on/off control in atemOSC for the Hyperdeck loop function. I generally have looping material running in three hyperdecks that I use for audio-visual performance. Is this something that could be easily added, given the play, stop, and clip number are all functional and working great? 

This would be an important feature, at least for me! 

Many thanks. 

Randall

**Comment by SteffeyDev** [comment]
Closing in favor of #178.  Sorry, totally didn't see this when I made the comment on #175 and merged it into #178.
