### ISSUE TITLE
Recording to external device support

### ISSUE THREAD

**Issue by shedthemusic** [SteffeyDev/atemOSC#171]
Is it possible to get the addresses for the rec and stop recording to disk functions for the ATEM MINI PRO?

Thanks in advance

Bob

**Comment by mkcologne** [comment]
You can do this with macros and recall them via OSC.
See also #158 
Cheers - M.

**Comment by mkcologne** [comment]
<Macro index="96" name="StartRec" description="">
        <Op id="RecordToMedia" start="True"/>
    </Macro>
    <Macro index="97" name="StopRec" description="">
        <Op id="RecordToMedia" start="False"/>
    </Macro>

**Comment by shedthemusic** [comment]
Thank you so much for this!

**Comment by SteffeyDev** [comment]
It looks like the SDK does support recording functions now, so I'll look into adding this into a later version.  In the meantime, macros is a great option

**Comment by SteffeyDev** [comment]
Actually, looks like this is a duplicate, closing in favor of #132.
