### ISSUE TITLE
Switcher connection issue

### ISSUE THREAD

**Issue by davidbs90** [SteffeyDev/atemOSC#172]
Hello,
I am working on trying to control my ATEM 2 M/E Production Studio 4K using Qlab. Attempting to use atemOSC as a bridge but it keeps giving the error "Could not create Switcher Discovery Instance.
ATEM Switcher Software may not be installed."

I have made sure the IP is correct but so far no success. Any other steps I can try to troubleshoot?

Thank you in advance!

atemOSC: v3.1.6
ATEM: Version 8.0.2
MacOS: Version 10.15.2

Connecting via ethernet.

<img width="418" alt="Screen Shot 2020-07-12 at 1 50 07 PM" src="https://user-images.githubusercontent.com/68200404/87254227-a1d3f980-c446-11ea-81cd-be05ce95380f.png">

**Comment by mkcologne** [comment]
Try Atem 8.2.3 Software or newer. That should work.

**Comment by SteffeyDev** [comment]
@davidbs90 Did you eventually figure it out?  Or still need help?

**Comment by davidbs90** [comment]
Upgraded the ATEM version and that fixed it. Thank you!
