### ISSUE TITLE
"No Response from Switcher" cannot connect

### ISSUE THREAD

**Issue by Soulglitchstudios** [SteffeyDev/atemOSC#173]
My issue is simple yet seemingly unresolvable.  I cannot connect atemOSC with my ATEM MINI.  I put in the IP address for the ATEM mini but it will not connect.  I know it's the correct IP Address since it is displayed in the ATEM Software control.  I've watched every youtube video on what seems to be a basic thing, and I've done exactly what everyone says to do and it seems to work for them, but my program simply will not connect.  I'm surprised that nobody else seems to have this issue but me, this is very frustrating.  Please help!!  I beg you, lol

**Comment by jruggles8** [comment]
I am having the same problem.   Does anyone have an idea?

**Comment by jruggles8** [comment]
Problem solved.  I read through the chain of problems and found that if I went back and downloaded 2.5.4.  When I changed to that version the switcher connected!!!

**Comment by maulican** [comment]
https://www.youtube.com/watch?v=HiajcVtgawc
