### ISSUE TITLE
List of Issues

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#175]
Greetings: I am working on a project with VDMX audio-visual software and am configuring pretty much all of the atemOSC commands. I am using using version 3.1.6. During the process I have come across a few issues, mostly Hyperdeck, I would like to share:

-- The Hyperdeck PLAY command (/atem/hyperdeck/1/play) is set to "play all files" rather than just play one file. You can see there is a partial ring around the play button when it is activated indicating it is in this "play all files" mode. It would be preferable to trigger the "play one file" mode, or, to make both modes available. 
-- The Hyperdeck CLIP TIME and TIMELINE TIME (/atem/hyperdeck/1/clip-time) (/atem/hyperdeck/1/timeline-time)commands do not work properly on on the Hyperdeck Mini, though they work fine on the Hyperdeck Studio. The problem is the timings are not accurate or there is no response. 
-- There is no command for toggling the LOOP feature on the Hyperdeck. Could this be added? Right now I am using a Macro. 
-- The TRANSITION types are not responding. I have tried both /atem/transition/set-type/mix as well as /atem/transition/set-type 'mix' as a string and neither works. 

Otherwise, everything is working great, including the audio functionality. Brilliant work, thank you!

Randall Packer

**Comment by carbon43** [comment]
Some of this may be specifically related to bugginess on BMD's end. The Hyperdeck Mini especially has had a slew of issues since release. 

In any case, it would be good to know your OS version as well, and maybe fire up Protokol to see if the strings are making it out of atemOSC, and in correct form. 

I agree that LOOP and the ability to play specific clips would be super useful!

![Screen Shot 2020-09-20 at 8 12 29 PM](https://user-images.githubusercontent.com/30049486/93725490-ba1a7000-fb7d-11ea-9f11-9f43c4efb97f.png)

**Comment by randallpacker** [comment]
Thanks David for your reply. 

I am using the latest version of Catalina, OS 10.15.6, and I'm on a iMac Pro. This chart is really helpful: it looks like there is a true/false message to send with play to choose between playing a selected clip or playing all clips. You can play a specific clip, by first choosing the clip and the sending play, though it would be nice to combine the commands. I have never used Protokol before but I'll look into that. 

Also, as I mentioned the Transitions types are not responding on my ATEM HD. 

Best, Randall

**Comment by carbon43** [comment]
One other thing that just occurred to me, I pulled that image from the Hyperdeck manual, I wonder if the full Hyperdeck API is exposed to the ATEM software/hardware, or if some commands only function via direct addressing of the Hyperdecks.

**Comment by randallpacker** [comment]
Actually the Hyperdeck commands are all working fine, at least with the Hyperdeck Studio. Tomorrow I'll add the boolean to Play to see if it toggles between play one clip and play all clips. 

The Hyperdeck protocols have completed changed the way I work, using my two Hyperdeck Studios as non-linear access, real-time video databases for live performance.

**Comment by carbon43** [comment]
Thats great to know, as Ive had them in the back of my mind for similar projects. Also they have proper frame for frame playout, which matters in some instances, vs the "best effort" of software based playout solutions.

**Comment by SteffeyDev** [comment]
* Ok, so play single clip is now covered in #178.
* Sounds like the clip-time and timeline-time issue is out of my hands (unless I'm not following this thread properly)
* I could totally add a feature for toggling looped playback mode. I'll open a new issue for that.
* I changed the API and removed the `set-type` command, hopefully you figured that out

Let me know if I missed anything.

@xenonheavyindustries I'm actually not using those commands behind the scenes.  Instead, I use the ATEM Switcher SDK to control hyperdecks through a switcher (at least for now).  Therefore, as far as atemOSC is concerned, you will need to look at the ATEM Switcher SDK manual to see what settings I can set.  Eventually we may allow direct connect to hyperdecks via the TCP protocol, at which point I would be using the the protocol commands you have attached, bug we are not there yet.
