### ISSUE TITLE
USK Size and Position OSC Address

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#176]
Hi,

can you add the addresses for the upstream-keyer 1 -> DVE -> position and size?
with macros i already programmed something like a digital zoom which works great, but i want to have a physical control in TouchOSC :-)
![ATEM_Mini_Pro_ISO](https://user-images.githubusercontent.com/66089559/94065513-893f7280-fdeb-11ea-8b8d-a6755ddf9e20.jpg)
Thanks in advance
Christoph

**Comment by randallpacker** [comment]
I would like to second this feature. It would be fantastic to have OSC control of position/size on all the keys.

**Comment by nick-shaw** [comment]
Thirded!

**Comment by xenonheavyindustries** [comment]
The USK may not be exposed in the API, per this thread: https://github.com/SteffeyDev/atemOSC/issues/168 

Might have to use Macros to do it, per @mkcologne . I havent checked myself recently, but may be doing some related work in the next week and can check then if I remember.

**Comment by SteffeyDev** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/10255587/102728072-abb42f80-42f7-11eb-92c2-80d866d1f704.png">

Looks like this are the only options the SDK has.  Not seeing anything to control the DVE position. I'll keep my eyes out though in case there is a different way of doing it

**Comment by nick-shaw** [comment]
Those are related to DVE as a transition. The useful parameters (to my way of looking at it) are the position and scale of the "flying key". This is (I believe) covered by the `IBMDSwitcherKeyFlyParameters` methods.

**Comment by SteffeyDev** [comment]
Ah right, is this the same ask as #156 then?

**Comment by nick-shaw** [comment]
Effectively, yes. #156 is about using it to animate position, and I am just thinking about placing a picture-in-picture with physical knobs. But it's the same parameters being affected.

**Comment by SteffeyDev** [comment]
I tested, this is ready for release.  You guys are correct, the DVE size and position are the same as the flying key size and position when using other modes.  After release, you will see the `/atem/usk/1/fly` set of addresses.

**Comment by SteffeyDev** [comment]
Released in 4.2.0, feel free to re-open if you have any issues with this feature

**Comment by davvidavvi** [comment]
Works beautifully! Thank you.
