### ISSUE TITLE
ATEM Audio input mute & AFV toggles

### ISSUE THREAD

**Issue by nic6020** [SteffeyDev/atemOSC#180]
Would it please be possible to have an address for Audio mute (on) button for each input?

Thanks
![Screen Shot 2020-10-02 at 4 52 39 pm](https://user-images.githubusercontent.com/72251426/94905630-c41e6600-04cf-11eb-9864-1c621e0f5aeb.png)

**Comment by bnmohr** [comment]
+1, as well as monitor and AFV if possible.  Though as with other detailed functions I can currently use macros to meet my needs.

**Comment by SteffeyDev** [comment]
Sounds good to me, I'll try to get this in the next release

**Comment by ruebyi** [comment]
Thank you! So I won‘t have to use Direct MIDI Controls anymore

**Comment by SteffeyDev** [comment]
Should be complete in latest release, 4.0.0. Feel free to re-open if not working right.

**Comment by SteffeyDev** [comment]
See documentation for usage
