### ISSUE TITLE
Hyperdeck Timecode Control Doesn't Recognize Frames

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#184]
Greetings all: 

Trick or Treat? 

Is there some reason why the atemOSC clip-time timecode message for Hyperdecks does not recognize frames? In the atemOSC documentation clip-time is specified as 00:00:00 (hours, minutes, seconds), but in the Blackmagic Hyperdeck protocol documentation timecode is specified as 00:00:00:00 (hours, minutes, seconds, frames). When I send a clip-time message including frames, it just resolves back to the beginning of the clip (00:00:00). 

Is there a workaround? Another way of doing this? I really need to trigger clip-time that includes frames for precise control. 

I have tested on a Hyperdeck Studio and a Hyperdeck Mini. 

Many thanks and Happy Halloween. 

Randall

**Comment by SteffeyDev** [comment]
Looking at the code, it looks like I forgot to implement handling for frames.  Sorry about that! I'll get that fixed in the next release.

**Comment by SteffeyDev** [comment]
Should be fixed in 4.0.0.  Feel free to re-open if not
