### ISSUE TITLE
Switching Program or Preview to anything above input 8 doesn't work

### ISSUE THREAD

**Issue by levranido1** [SteffeyDev/atemOSC#187]
Hey!

When trying to switch the program or preview to Media player 1 & 2 or color bars or anything higher then input 8 nothing happens.
I tried wiresharking the UDP it's sending the switcher, and it seems different in those numbers then what the one form the ATEM software looks like - maybe it's related?

Thanks!

**Comment by SteffeyDev** [comment]
Have you looked at the atemOSC log yet? Probably more useful than wireshark for debugging imho. You can also check the built in addresses list to make sure atemOSC sees those higher numbers as valid, often they might be weird numbers like 1003 instead of following after 8.

**Comment by levranido1** [comment]
When I look at the log for atemOSC it shows me only the input commands right?
and it does show 1-12

**Comment by SteffeyDev** [comment]
The log should show every single command you send, and any issues it has processing them

**Comment by SteffeyDev** [comment]
@levranido1 Are you still having issues?

**Comment by levranido1** [comment]
Hey!

Yes. It never worked.
And there’s no visible error anywhere.

Ido.

**Comment by SteffeyDev** [comment]
Ok, what version of atemOSC are you running? Also, can you paste the full log here that you get when attempting to send the commands that don't produce any change?

**Comment by levranido1** [comment]
Hey Peter!

I just looked again, and I wonder if there's been an update to the
documentation.
I see now that it says to use 3010 to switch to MP1, but I could swear it
was something like 11 or 13 before.
In anycase, it works with 3010. so It's all good.

Sorry if this was just a misread on my part!
And thank you for the support!

Ido.

**Comment by SteffeyDev** [comment]
Excellent, good to hear! Of course, the documentation is frequently being updated, so it is very possible to have led you astray in the past.
