### ISSUE TITLE
ATEM mini Pro doesn't work over USB, but Atem Mini (not Pro) does?

### ISSUE THREAD

**Issue by jeffreylsoffer** [SteffeyDev/atemOSC#188]
Hi!

I know this isn't documented as an actual feature, but I was amazed to find my ATEM mini was able to be recognized over USB as long as the IP matched what was in the blackmagic atem setup software.

When I tried this with an ATEM Mini Pro, it didn't work until I attached an ethernet cable from the ATEM to my laptop (which is how I _assumed_ this would only work). Any idea why this is the case and/or how to get the Pro to behave the same as the non-Pro? Would be amazing to ditch this extra wire and control over USB.

**Comment by jeffreylsoffer** [comment]
Turns out the issue was I had the Blackmagic Software and atemOSC open at the same time, which _doesn't_ let both work over USB. So, closing the Blackmagic software and re-launching atemOSC allowed USB control. Super cool!

**Comment by jeffreylsoffer** [comment]
Hi!

Is it possible the new changes in v4.x broke USB support? I know this is a kinda unsupported use-case, but it worked pretty well in v3.1.6. Basically as long as an ATEM mini was connected, Blackmagic's software was closed and a random IP was inserted into atemOSC, it connected automatically! No ethernet cable required.

v3.1.6 is fine for now, but would love to not have to hold on to an old version.

**Comment by SteffeyDev** [comment]
I don't think anything I changed would cause it, but the latest BlackMagic ATEM SDK (8.6) may have made changes, compared to the SDK used in version 3.1.6 (8.1). AtemOSC is just a wrapper around the BlackMagic ATEM SDK, so if they changed how things worked under the hood I have no control over that.

**Comment by SteffeyDev** [comment]
For instance, I just tell the SDK to connect to a switcher at a given IP address, and the SDK handles how to make that connection.

**Comment by SteffeyDev** [comment]
As far as I know, there's no way for me to tell the SDK to connect over USB instead of the network.

**Comment by jeffreylsoffer** [comment]
Thanks Steffey! Wasn't able to get it to work so I guess it's an ATEM SDK thing. I think I'm gonna move toward using Ethernet in the future to avoid the struggle. Thanks anyway!
