### ISSUE TITLE
ATEM Constellation 8K - ME2 Control

### ISSUE THREAD

**Issue by davidbs90** [SteffeyDev/atemOSC#192]
More of a question than issue.

I am attempting to control ME2 on a Constellation 8K. Attempting the line mentioned in the OSC description:
**/atem/me/2/preview <number>**

However I am getting the error "OSC endpoint not implemented"
Wanted to see if there is an adjustment I need to make to the command on my end?

atemOSC: 3.1.6
ATEM version: 8.5

<img width="387" alt="Screen Shot 2021-01-18 at 6 56 32 PM" src="https://user-images.githubusercontent.com/68200404/104974977-0b692d80-59bf-11eb-8e19-2b3ada0f4777.png">

**Comment by SteffeyDev** [comment]
Yep, I haven't released the 2 M/E version yet. Hoping to get that out in the next week or two, but it depends on how difficult the new signing process is.

**Comment by SteffeyDev** [comment]
Keep an eye on the releases and on #2 for when I release this next version.

**Comment by SteffeyDev** [comment]
Let me know if you would be interested in testing out a (probably buggy) pre-release version in the near future.

**Comment by davidbs90** [comment]
Certainly! We are running the constellation which has the 4 ME's.
Our team would not mind testing at all.

**Comment by SteffeyDev** [comment]
Great! Please send me an email, steffeydev@icloud.com
