### ISSUE TITLE
OSC Feedback for AUX Output

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#194]
Hi there,

i´m using an APC mini Midi Controller and assigned buttons also to preview inputs/preview/program/multiview thru the atem minis hdmi output.
can you add feedback to those osc adresses please? this would be great to see whats going on (buttons can have multiple colors on this controller)
/atem/aux/1 1
/atem/aux/1 2
/atem/aux/1 3
/atem/aux/1 4
/atem/aux/1 9001 for multiview, 10010 for program, 10011 for preview

Edit: and please also add feedback if atem/transition/ftb is on or off....

thank you so much :-)

**Comment by SteffeyDev** [comment]
Added in v4.1.0
