### ISSUE TITLE
Multiple Feedback Devices

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#195]
hi Peter,
as mentioned by email:
can you implement send feedback from switcher to multiple OSC devices? I made a copy of the app and it works, but because the app reads its values when starting it is an unstable solution - and since you can connect only 5 times to same switch you will run out of numbers soon...so it´s mandatory that all connections are bundled together, so even if you connect 10 devices through atemOSC to the same mixer it uses only one connection.

Solution can be: add another 2 or 3 rows for feedback messages (or just a add more button)
<img width="374" alt="feedback" src="https://user-images.githubusercontent.com/66089559/106368256-a0b5db80-6348-11eb-90b6-07479b226eda.png">

Through this an easy tally system can be built by the way using touchOSC or whatever :-)

**Comment by SteffeyDev** [comment]
Until I have time to work on this, you can try setting the IP to 192.168.188.255 (assuming a /24), which will broadcast the messages to every device on the subnet.

**Comment by Christoph111** [comment]
wow didn´t know that :-)
works perfect for now

Am 30.01.2021 um 22:21 schrieb Peter Steffey <notifications@github.com>:


Until I have time to work on this, you can try setting the IP to 192.168.188.255 (assuming a /24), which will broadcast the messages to every device on the subnet.

**Comment by SteffeyDev** [comment]
I think using a broadcast address is the proper solution to this problem, assuming that is not blocked on the network level. Going to close this, open a support ticket on www.atemosc.com/support if there are any issues with this.
