### ISSUE TITLE
Macro status Feedback

### ISSUE THREAD

**Issue by mrbossitaly** [SteffeyDev/atemOSC#196]
Hi people,

great job at all!!! 
Yesterday I've finished to map (osculator+APCMini) my controller for ATEM Mini.
For a future release should be possible to add for macro **GetRunStatus** feedback from switcher to permit on controller a light feed if the macro is still running or have finished its execution.

Many tnx for your attention.

MrBossItaly

**Comment by SteffeyDev** [comment]
Finished testing, will be included in next release

**Comment by SteffeyDev** [comment]
Released in 4.2.0, feel free to re-open if you have any issues with this feature
