### ISSUE TITLE
Refresh or Load Still in Media Pool

### ISSUE THREAD

**Issue by nickvoll** [SteffeyDev/atemOSC#197]
It would be helpful to have a command to refresh or load an image into the media pool.  The ATEM plugin for photoshop does this automatically, so I would think this option might be possible.  If I have a lower third or other graphic loaded in MP1, and I need to update it with a new still that is not already in the media pool, it would be great to be able to do it with a single button press in my client, rather than a series of mouse actions in the ATEM or Photoshop. #

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com/support would make it a higher priority for me.
