### ISSUE TITLE
Hyperdeck Studio Mini runtime timecode display in TouchOSC?

### ISSUE THREAD

**Issue by editormixer** [SteffeyDev/atemOSC#198]
hi, can someone explain how to get the Hyperdeck Studio Mini's runtime timecode to display in TouchOSC? 
I'm making a TouchOSC label using "/atem/hyperdeck/1/clip-time" and "/atem/hyperdeck/1/timeline-time" both with no luck. Any help would be appreciated.
Thanks!

**Comment by SteffeyDev** [comment]
Can you confirm that the Out IP Address is the same IP address as the iPad running TouchOSC and that the Out Port matches the port that TouchOSC is listening on?

**Comment by editormixer** [comment]
yes, the Macros correctly display their names and descriptions, and all other feedback is working. With the 4.0 update, both "clip-time" and "timeline-time" now display "00:00:00" (looks like frames are missing) but neither of these display actual time-just zeroes.

**Comment by SteffeyDev** [comment]
Ok, I'll check it out and see if I can spot an issue. Don't actually have any hyperdecks to test with unfortunately.

**Comment by SteffeyDev** [comment]
Are you getting other feedback from Hyperdecks, such as the state when you play or pause?  Also, if you log all feedback do you see it, maybe with a different ID than expected?
