### ISSUE TITLE
v4.0-no feedback in audio mix option?

### ISSUE THREAD

**Issue by editormixer** [SteffeyDev/atemOSC#201]
It appears as the audio Mix Option is not sending feedback.

**Comment by SteffeyDev** [comment]
What kind of switcher do you have?

**Comment by editormixer** [comment]
I have an ATEM Television Studio HD and a Mini Pro ISO. I've not tested with the Mini Pro ISO yet, but there's definitely no feedback being sent from the Television Studio HD. Let me see what the Mini Pro ISO is doing.

**Comment by SteffeyDev** [comment]
Ok, let me know what you find. I don't have a television studio to test with, but I'll try it out on some different switchers next time I can and see if I can reproduce.

**Comment by SteffeyDev** [comment]
Are you getting feedback for balance and gain on the input that you are not getting mix feedback for?
