### ISSUE TITLE
status feedback Transition bar

### ISSUE THREAD

**Issue by ruebyi** [SteffeyDev/atemOSC#203]
Hi,
I think I found a bug?

When using the "Auto" Transition or my Bar I receive the T-Bar status via 
/atem/transition/bar f 0.0 (etc)

BUT I receive this message not one time only, but 3 Times - is there a reason for that or is it just a bug?

Thank you for your great work!
4.0 is awesome!

**Comment by SteffeyDev** [comment]
You should receive continuous feedback when the bar changes, throughout the auto transition and when controlling the bar externally. If you move the bar in ATEM software control and don't receive messages reflecting the current bar position (between 0.0 and 1.0), then that would be a bug. I'll test it out next time I get the chance.

**Comment by ruebyi** [comment]
I get constant feedback, but when I stop I receive the final Message of the movement (/atem/transition/bar f0.0 OR /atem/transition/bra f1.0) three times - two of them at the exact same ms (that's what osculator says.

**Comment by SteffeyDev** [comment]
Ok, so to make sure I understand, you receive the intermediate messages once but the final message 3 times?

**Comment by ruebyi** [comment]
Yes, perfect!
The first message comes in - then I get the whole Status updates for all other inputs and so on, and in the end I get the final message two times again

**Comment by SteffeyDev** [comment]
Ok, great. All I have to do is check whether atemOSC is creating the duplicates, or whether it is the switcher itself. If it is the switcher itself, there's not much more I can do except open an issue with their developers.

**Comment by SteffeyDev** [comment]
@ruebyi Preliminary testing indicates that the bug is on the BlackMagic side of things, is there any issues or negative side-effects of this bug? It might also be intentional for them, I'm not sure what they intended.

**Comment by ruebyi** [comment]
Well the negative ist, that I'm not able to trigger an event in Osculator when this Value is reached, but I managed to do a workaround, so it's not essential for my work
