### ISSUE TITLE
Could not create Switcher Discovery Instance

### ISSUE THREAD

**Issue by jaredsking123** [SteffeyDev/atemOSC#204]
Hello! 

When starting version 4.0 I am getting the following error: "Could not create switcher discovery instance". I am running ATEM Control 8.1.1 locally on the same machine as AtemOSC 4.0 - ATEM Control connects fine, but 4.0 is erroring.
Any thoughts?

<img width="1466" alt="Screen Shot 2021-02-24 at 3 42 12 PM" src="https://user-images.githubusercontent.com/71047038/109081664-7b9e5980-76b7-11eb-97d1-9d8a6dcc338d.png">

**Comment by SteffeyDev** [comment]
You probably need to update your ATEM software version, or use an older version of atemOSC that supports 8.1.1

**Comment by jaredsking123** [comment]
Thanks Steffey,

I figured that was the case. I know a lot of people who would like to be using atemOSC but own various ATEM models that all have to be on one version on ATEM Control for one reason or another (Constellation 8Ks, vs. smaller Broadcast 4Ks, etc), making the version control between the control SW and atemOSC a bit of a sticking point. Is there any reason the latest version couldn't be expanded to interface with legacy versions of Control? Maybe a drop down menu for the Control version you're linking to? That would be a great improvement to an already awesome product. 

Regardless - Awesome App! Keep up the good work. Our productions are loving it. 

Thanks!

**Comment by SteffeyDev** [comment]
I wish it was that simple. All I do is drop in the latest SDK from BlackMagic, I have almost no control over backward comparability of their SDK. I could drop in an older SDK and remove any features that didn't exist with that, but no easy way of knowing which SDKs support which product and version ranges, and would also be a ton of work for me unfortunately.

**Comment by SteffeyDev** [comment]
I could explain better in technical terms, but in short BlackMagic SDK is the reason I can't, and it's outside my control. Maybe I could contact them about it, but can't imagine SDK backward compatibility is a huge priority for them either. Could be wrong though.
