### ISSUE TITLE
Mac M1 or Big Sur incompatibility?

### ISSUE THREAD

**Issue by tbar0970** [SteffeyDev/atemOSC#206]
I was experiencing the error "Could not create Switcher Discovery Instance. ATEM Switcher Software may not be installed." mentioned in Issue #205.  Waited for the latest  atemOSC release which supports the 8.6 SDK, but the problem persisted on my M1 mac mini.

So then I tried on my older intel macbook air (MacOS 10.15.7) and it seems to work fine.

This suggests an issue on the M1 specifically or perhaps Big Sur in general ?

**Comment by lewisjoss** [comment]
I am also having this issue with a Mac mini - M1 chip. Updated to latest but happens. I've just replaced my Mac in my show rack with a new M1 Mac. So I'm hoping there will be a fix or workaround :-)

**Comment by SteffeyDev** [comment]
Yep, I'll close this in favor of #205
