### ISSUE TITLE
atemOSC 4.1 crashing periodically

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#207]
Greetings all:

I am now using atemOSC 4.1 with all cylinders firing, including two ATEM HD switchers, 3 Hyperdecks, and pretty much all the various control parameters. It's working quite well, it's really a great piece of work Peter! 

However, I am experiencing occasional crashes. Here is the Mac OS crash log. 
[atemOSC Crash.docx](https://github.com/SteffeyDev/atemOSC/files/6176351/atemOSC.Crash.docx)

I am not very good at reading crash logs but it appears it may be the Apple Connection Kit I have connected to my iMac Pro, where the atemOSC software is running. I have the ATEM software Control running on a different computer, not sure if that matters. I still haven't updated all of my OSC commands in VDMX, but I'm not not sure if that could be an issue. I am also getting a steady stream of feedback from the Hyperdecks while they are running. 

When atemOSC crashes, I get the Apple crash report, and am able to reopen and resume working order. 

I am curious if there are any insights on this crash issue. 

Many thanks, 

Randall

**Comment by randallpacker** [comment]
Attached is another is another crash log:
[atemOSC Crash_1.docx](https://github.com/SteffeyDev/atemOSC/files/6176482/atemOSC.Crash_1.docx)

I see the Crash is at Thread 4: 

> Crashed Thread:        4
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> dyld: in dlopen_preflight()
> abort() called
> atemOSC(31296,0x7000109d2000) malloc: double free for ptr 0x7f84683c8000

And the crash occurred just as a Program Source was changed. 

I am using ATEM Software Control version 8.5.3. Mac OS Catalina. 

Should I try upgrading to 8.6? Is there a newer version of atemOSC than 4.1 I can try? 

Many thanks, 

Randall

**Comment by randallpacker** [comment]
I just noticed that it is recommended to download atemOSC.debug.zip associated with the version I am using, in order to isolate the crash, but where is this zip file found?

**Comment by SteffeyDev** [comment]
Looks like the issue is with the `[NSTextView(NSPrivate) _scrollRangeToVisible:forceCenter:]` function, which I use to always show latest log entry.  Looking around the internets now, obviously silly for a log to crash the app.  Hoping to find a solution, but if I don't I'll disable log auto-scroll by default to prevent this

**Comment by SteffeyDev** [comment]
The `atemOSC.debug.zip` was a note for my future self, but I can't produce it right now since I'm signing and notarizing the app

**Comment by SteffeyDev** [comment]
How long between opening the app and the crash? Hours? Minutes?

**Comment by randallpacker** [comment]
Hi Peter, 

 

Wow, logging crash!! 

 

The crash seems to occur anywhere from 5 to 15 minutes depending upon the activity. The logging make sense, since it seems to take a little longer to crash when there is no real-time data coming back from the Hyperdecks. 

 

I tried to prevent feedback but I couldn’t figure out how to stop it without confusing the app. 

 

I can’t thank you enough!! 

 

Randall

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 12:30 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

How long between opening the app and the crash? Hours? Minutes?

**Comment by SteffeyDev** [comment]
Ok, I emailed you a potential fixed version to test. With crashing that frequently, I'm wondering if the amount of text in the log is what causes the issue to manifest.

**Comment by randallpacker** [comment]
Hi Peter, I am trying to install it, very finicky about copying the app, but if I save it to my NAS I can open it from there. Just about to start testing. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 1:43 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, I emailed you a potential fixed version to test. With crashing that frequently, I'm wondering if the amount of text in the log is what causes the issue to manifest.

**Comment by randallpacker** [comment]
It’s running now, we’ll see how long it takes before a crash.

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 1:43 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, I emailed you a potential fixed version to test. With crashing that frequently, I'm wondering if the amount of text in the log is what causes the issue to manifest.

**Comment by randallpacker** [comment]
Still working for about 30 minutes! 

 

Forgot to mention that I would first get the spinning wheel, but it would still be working, then a few minutes later the complete crash. 

 

For now… looking good! I’ll give it another half hour or so to be sure. 

 

 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 1:50 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

It’s running now, we’ll see how long it takes before a crash.

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 1:43 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, I emailed you a potential fixed version to test. With crashing that frequently, I'm wondering if the amount of text in the log is what causes the issue to manifest.

**Comment by randallpacker** [comment]
Just turned on one of the Hyperdecks and the wheel almost immediately started spinning, so it is absolutely the amount data coming in given all the real-time feedback. 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 2:15 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Still working for about 30 minutes! 

 

Forgot to mention that I would first get the spinning wheel, but it would still be working, then a few minutes later the complete crash. 

 

For now… looking good! I’ll give it another half hour or so to be sure. 

 

 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 1:50 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

It’s running now, we’ll see how long it takes before a crash.

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 1:43 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, I emailed you a potential fixed version to test. With crashing that frequently, I'm wondering if the amount of text in the log is what causes the issue to manifest.

**Comment by SteffeyDev** [comment]
Good to hear! How much text do you think you get in the logs during a production? I’ve been wondering if I need to cap the amount of logs stored at some point to prevent bloat and crashes. Are you looking at 5 lines per second? 10? 50?

Peter Steffey

**Comment by randallpacker** [comment]
I’m running it again with the hyperdeck on from the beginning in order to time it more accurately. I have attached the app so you can see the setup and the feedback. 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 2:18 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Just turned on one of the Hyperdecks and the wheel almost immediately started spinning, so it is absolutely the amount data coming in given all the real-time feedback. 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 2:15 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Still working for about 30 minutes! 

 

Forgot to mention that I would first get the spinning wheel, but it would still be working, then a few minutes later the complete crash. 

 

For now… looking good! I’ll give it another half hour or so to be sure. 

 

 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 1:50 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

It’s running now, we’ll see how long it takes before a crash.

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 1:43 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, I emailed you a potential fixed version to test. With crashing that frequently, I'm wondering if the amount of text in the log is what causes the issue to manifest.

**Comment by SteffeyDev** [comment]
Ok, if you get a new crash log please send that as well.

Peter Steffey

**Comment by randallpacker** [comment]
Just took 10 minutes for the wheel to start turning with the hyperdeck on. I have to wait a little longer for the actual crash before it generates a log (I believe). Will send as soon as I have it. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 2:26 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, if you get a new crash log please send that as well.

Peter Steffey

**Comment by randallpacker** [comment]
I am testing one more time just to be sure I had the right version… I just named it so I can identify for sure it’s the latest you sent me. I am guessing it will take about 10 to 20 minutes before the actual crash occurs after the wheel starts turning. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 2:26 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, if you get a new crash log please send that as well.

Peter Steffey

**Comment by SteffeyDev** [comment]
I’ll probably go ahead and limit the number of stored log lines and send that to you for testing soon.

Peter Steffey

**Comment by randallpacker** [comment]
Just saw this note. Yes, I would say around 5 lines per second with one Hyperdeck running and a source change every 10 seconds or so. I imagine it would be closer to 15 lines per second with all three hyperdecks running.  

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 2:19 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Good to hear! How much text do you think you get in the logs during a production? I’ve been wondering if I need to cap the amount of logs stored at some point to prevent bloat and crashes. Are you looking at 5 lines per second? 10? 50?

Peter Steffey

**Comment by randallpacker** [comment]
Perhaps it would also be good to be able to clear the log. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 2:36 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

I’ll probably go ahead and limit the number of stored log lines and send that to you for testing soon.

Peter Steffey

**Comment by randallpacker** [comment]
Wheel still spinning, it seems to take a while before the actual crash. I guess it has to suffocate first! 😉 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 2:45 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Perhaps it would also be good to be able to clear the log. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 2:36 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

I’ll probably go ahead and limit the number of stored log lines and send that to you for testing soon.

Peter Steffey

**Comment by randallpacker** [comment]
Finally crashed, I have attached the log. Thx! 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 2:58 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Wheel still spinning, it seems to take a while before the actual crash. I guess it has to suffocate first! 😉 

 

From: RANDALL PACKER ***@***.***>
Date: Sunday, March 21, 2021 at 2:45 PM
To: SteffeyDev/atemOSC ***@***.***>, SteffeyDev/atemOSC ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Perhaps it would also be good to be able to clear the log. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 2:36 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

I’ll probably go ahead and limit the number of stored log lines and send that to you for testing soon.

Peter Steffey

**Comment by SteffeyDev** [comment]
Ok, I had to just completely re-write the log view to achieve what I want, but try this latest version: https://app.box.com/s/8p1k7kny92j38j0apg3z51jqku54y7yc

Two things I added:

• Only stores last 2000 log entries (should prevent atemOSC from using too much memory
• Pauses updates when you scroll up to view previous log entries (a pet peeve of mine that has been annoying for a while)

I tested locally, was able to handle 20 messages per second with no issue, when I started sending 100 messages per second it started struggling a bit. Let me know how it works for you.

Hope this helps,
Peter Steffey

**Comment by randallpacker** [comment]
Thanks Peter, but unable to open the app on either of two different machines, one an iMac Pro running Catalina, the other a MacBookPro M1 running Big Sur. Need to run it on the Catalina machine but thought I would try both. 

 

Randall

 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 10:12 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, I had to just completely re-write the log view to achieve what I want, but try this latest version: https://app.box.com/s/8p1k7kny92j38j0apg3z51jqku54y7yc

Two things I added:

• Only stores last 2000 log entries (should prevent atemOSC from using too much memory
• Pauses updates when you scroll up to view previous log entries (a pet peeve of mine that has been annoying for a while)

I tested locally, was able to handle 20 messages per second with no issue, when I started sending 100 messages per second it started struggling a bit. Let me know how it works for you.

Hope this helps,
Peter Steffey

**Comment by SteffeyDev** [comment]
That’s weird, can you be more specific about “Unable to Open”? Do you get an error message? What do you see?

Peter Steffey

**Comment by randallpacker** [comment]
Hi Peter, 

 

Finally getting to all your emails. 

 

It takes about 10 minutes for the wheel to start spinning, but the app is still working for another 30 minutes to an hour before it actually crashes and quits. 

 

Randall

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 12:30 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

How long between opening the app and the crash? Hours? Minutes?

**Comment by randallpacker** [comment]
Did you see the screenshots? I just took another one, and it seems you sent me the app rather than the dmg installer. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Monday, March 22, 2021 at 7:45 AM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

That’s weird, can you be more specific about “Unable to Open”? Do you get an error message? What do you see?

Peter Steffey

**Comment by randallpacker** [comment]
Sadly… with all three hyperdecks running I now have the spinning wheel after about 15 minutes. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Sunday, March 21, 2021 at 12:18 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

The atemOSC.debug.zip was a note for my future self, but I can't produce it right now since I'm signing and notarizing the app

**Comment by SteffeyDev** [comment]
Ok, re-run the test then but try this: after running for a minute, scroll back up in the log to look at some previous log entry, and leave it there.  This will pause loading new log entries. Then continue running the test and see what happens.  Because the log is now capped at 2000 entries, there should be nothing that changes between 3 minutes and 15 minutes, but that might help me understand the issue.  Obviously, make sure you are running 4.1.2.  I’ll also need crash logs once you get them, I’ve changed the code so much that none of the previous crash logs you sent are relevant, since the code they reference is gone.

Peter Steffey

**Comment by randallpacker** [comment]
Still waiting for the current spinning wheel to crash. I am about to run off to the dentist, back in a couple of hours and by then I’ll have the first crash log, and then I’ll run the second test. 

 

Thanks! 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Monday, March 22, 2021 at 9:42 AM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, re-run the test then but try this: after running for a minute, scroll back up in the log to look at some previous log entry, and leave it there.  This will pause loading new log entries. Then continue running the test and see what happens.  Because the log is now capped at 2000 entries, there should be nothing that changes between 3 minutes and 15 minutes, but that might help me understand the issue.  Obviously, make sure you are running 4.1.2.  I’ll also need crash logs once you get them, I’ve changed the code so much that none of the previous crash logs you sent are relevant, since the code they reference is gone.

Peter Steffey

**Comment by randallpacker** [comment]
Will try the test in a few minutes, but wanted to let you know that 4.1.2 never crashed after almost 3 hours, the wheel is just spinning and the app is still functioning. 

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Monday, March 22, 2021 at 9:42 AM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, re-run the test then but try this: after running for a minute, scroll back up in the log to look at some previous log entry, and leave it there.  This will pause loading new log entries. Then continue running the test and see what happens.  Because the log is now capped at 2000 entries, there should be nothing that changes between 3 minutes and 15 minutes, but that might help me understand the issue.  Obviously, make sure you are running 4.1.2.  I’ll also need crash logs once you get them, I’ve changed the code so much that none of the previous crash logs you sent are relevant, since the code they reference is gone.

Peter Steffey

**Comment by randallpacker** [comment]
Hi Peter, no crash log on the first test because it never crashed, just hung with the wheel though still working. So I had to force quit. (By the way, are you going to activate the quit command?)

 

I am now running the second test. However, when I scroll up, it keeps on logging and the scroller drops back down to the bottom of the scroll bar. Is it supposed to do that? Yes, I am using 4.1.2. Same three hyperdecks and changing sources every few seconds. 

 

I can’t guarantee I can get a crash log because it doesn’t seem to crash (not sure if that is good or bad!), but I’ll let it turn for a while and at least see how long it takes for it to hang up. 

 

In fact, in the time it took to write this email, it is already hung up with the wheel, but still working. It seems in this state that everything is working, you just can’t click on the interface without getting the turning ball, so you have no access to the controls. 

 

Randall

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Monday, March 22, 2021 at 9:42 AM
To: SteffeyDev/atemOSC ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] atemOSC 4.1 crashing periodically (#207)

 

Ok, re-run the test then but try this: after running for a minute, scroll back up in the log to look at some previous log entry, and leave it there.  This will pause loading new log entries. Then continue running the test and see what happens.  Because the log is now capped at 2000 entries, there should be nothing that changes between 3 minutes and 15 minutes, but that might help me understand the issue.  Obviously, make sure you are running 4.1.2.  I’ll also need crash logs once you get them, I’ve changed the code so much that none of the previous crash logs you sent are relevant, since the code they reference is gone.

Peter Steffey

**Comment by MikeFumbler** [comment]
To all,

I got the same issue. 4.1 crashes within 5 minutes after using some fader movements for audio channels on my ATEM Mini Extreme. (Using OSCulator with some MIDI data scaling). First beachballing, and than the imminent crash.

It the sluggishness of fader movements in the ATEM SC the ATEM software itself?

Thanks for your amazing work.

**Comment by SteffeyDev** [comment]
I actually have a fix for this ready, I'll try to release this weekend.

**Comment by MikeFumbler** [comment]
Great!
I will test it and report as soon as I can.

**Comment by SteffeyDev** [comment]
Ok, fixed in 4.1.4
