### ISSUE TITLE
Muting audio channel for ATEM Mini Pro ISO (I assume any ATEM) - Feature Request

### ISSUE THREAD

**Issue by JohanNiklasson** [SteffeyDev/atemOSC#208]
Hi

I would like to be able to mute the audio on the six main channels.

I am using an XTouch Mini and have routed the knobs to adjust the volume. By pressing the knobs, I would like to mute the audio channel completely. The ATEM Software Control offers the option to turn the audio channel on or off.

**I see no "audio mute" address listed so I kindly ask for you to consider adding that.**

Thank you!

Best Regards
Johan Niklasson

**Comment by ruebyi** [comment]
Works perfectly with

`/atem/audio/input/$i/mix <string>
Where <string> is 'on', 'off', or 'afv' (audio follow video) `

**Comment by JohanNiklasson** [comment]
> Works perfectly with
> 
> `/atem/audio/input/$i/mix <string> Where <string> is 'on', 'off', or 'afv' (audio follow video)`

Thanks - I am sorry, I did not read the list properly - it is clearly listed there.

Followup: I can turn the audio channel 'on' - **how do I make the next press of the button turn it back 'off'?**

Best Regards
Johan Niklasson

**Comment by SteffeyDev** [comment]
I'm not familiar with XTouch Mini, is it MIDI to OSCulator or does it send OSC directly?

**Comment by ruebyi** [comment]
it's midi - I'm using an Korg NanoKontrol 2 For Audio Control, so I have 3 Buttons for all 3 Functions...

Are you using Osculator?

**Comment by JohanNiklasson** [comment]
> it's midi - I'm using an Korg NanoKontrol 2 For Audio Control, so I have 3 Buttons for all 3 Functions...
> 
> Are you using Osculator?

Yes, I am using OSCulator. 

**Do you know how I can get the same button to turn 'off' audio and then turn 'on' audio? The same button doing both?**

Best Regards
Johan Niklasson

**Comment by ruebyi** [comment]
it's possible
I will try to make a example project today or tomorrow - remind me kindly if I forget to do this

**Comment by JohanNiklasson** [comment]
> it's possible
> I will try to make a example project today or tomorrow - remind me kindly if I forget to do this

I would love to see what you come up with. Thank you.

Best Regards
Johan Niklasson

**Comment by ruebyi** [comment]
I worked on it for a few minutes - but it does not work as expected.
I'm able to make an Toggle event, but I don't find a way to trigger the message with the same button...

**Comment by SteffeyDev** [comment]
Sounds like another use case for an audio on/off toggle address, similar to #202. I might add that in the next version, so that there is a /toggle address that could toggle between audio mix options.  Do you want to toggle between on/off, or off/afv? Is there ever a use case for toggle between on/afv?

**Comment by ruebyi** [comment]
usually between on/off and afv/off

Thanks - I think it's only an Osculator issue, but perhaps I'm to stupid to solve it

**Comment by SteffeyDev** [comment]
Unless OSCulator can store state, I don't see how you could solve it with just OSCulator. The same button doesn't know the current mix state, so can't know what to change it to next. atemOSC is stateless as well, which is why it can't duplicate ATEM software control toggles (which are stateful).

**Comment by ruebyi** [comment]
Osculator can store an on/off state of a command - that's what I'm using

And it can store Variables

**Comment by SteffeyDev** [comment]
Ok that's pretty cool, also way outside my knowledge. So you could store a flag when the button is pressed which would change the OSC command to send a different mix value next time?

**Comment by ruebyi** [comment]
in theory, yes... But I'm not able to figure it out...

**Comment by ruebyi** [comment]
I did it!
Hope it helps!
[toggle button test.zip](https://github.com/SteffeyDev/atemOSC/files/6185384/toggle.button.test.zip)
