### ISSUE TITLE
DSK Mask controls

### ISSUE THREAD

**Issue by mark-epstein** [SteffeyDev/atemOSC#209]
Can you mask settings on the DSKs be controlled?

This may be the wrong way to do it but I use the DSK mask for lower thirds (translucent black) and for side-by-side (opaque) sermon slides.  My ATEM only has two DSKs so my options are limited to those two, but if I could change the mask on the fly, that would give me many more options.

**Comment by SteffeyDev** [comment]
Note to self: We're looking at the SetMaskBottom, SetMaskTop, SetMaskLeft, and SetMaskRight functions

**Comment by randallpacker** [comment]
That would be awesome Peter! I definitely could use that.

**Comment by Christoph111** [comment]
you need someone to test? let me know

**Comment by SteffeyDev** [comment]
I tested and this is working, will be included in next release

**Comment by SteffeyDev** [comment]
Released in 4.2.0, feel free to re-open if you have any issues with this feature
