### ISSUE TITLE
Record Control for Connected Cameras via OSC

### ISSUE THREAD

**Issue by jaredsking123** [SteffeyDev/atemOSC#211]
Hi There!

I'd like to submit a feature request:

BMD cameras look to support start/stop record triggering via embedded ANC on their SDI return line in addition to all the paint/color controls for which you've already supported. In the same way atemOSC offers remote triggering of connected Hyperdecks, an extremely useful feature would be remote start/stop triggering of these same camera IDs.

Thoughts?

**Comment by SteffeyDev** [comment]
Sounds good to me, #107 is one of the next features I'll work on, so I'd probably do this at the same time.

**Comment by jaredsking123** [comment]
Awesome, thanks so much. Looking forward to this!

**Comment by SteffeyDev** [comment]
Going to have to delay this feature, see notes on #107

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com/support would make it a higher priority for me.
