### ISSUE TITLE
Hyperdeck Countdown (Time Remaining) for clips

### ISSUE THREAD

**Issue by jakekenner** [SteffeyDev/atemOSC#212]
Hey there! Just wondering if there is any way to get the time remaining out of a hyperdeck clip rather than just the timecode value (atem/hyperdeck/$i/clip-time). That way you can have really useful displays for talent or crew that count you down to the end of a video.

ATEM Software Control and any hardware panels have access to that information from the deck so I don't know if it would be possible to pull that information from the switcher somehow??

**Comment by randallpacker** [comment]
Yes, this would be very powerful. Using software such as Max MSP, you could use the countdown to 0 as a trigger without even having to know the actual duration of the clip. The end of the clip in my setup could auto-transition from a Hyperdeck to Camera without having to worry about the timing. Like having an automated engineer!

**Comment by SteffeyDev** [comment]
Unfortunately, I have no way via the SDK to get either the time remaining, or the length of the current clip to calculate the time remaining.  I'll reach out to the ATEM developers to see if they can add that in a future version of the SDK.

**Comment by randallpacker** [comment]
thanks Peter for going to bat for us.

**Comment by SteffeyDev** [comment]
I missed something in the SDK, it looks like this is possible after all!

**Comment by ldhall1856** [comment]
Any update on this? Time remaining would be a great feature!

**Comment by SteffeyDev** [comment]
Unfortunately not, it's a busy season of life now so I haven't had time to work on this for a bit

**Comment by SteffeyDev** [comment]
I've released a [new major version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0) which includes much more HyperDeck feedback, so give that a try and see if it helps. I don't have it sending out the new time remaining every second, however, so please open a support ticket at www.atemosc.com/support if you still want that and I could probably and that as an opt-in feature.
