### ISSUE TITLE
Switcher Discovery Issue

### ISSUE THREAD

**Issue by SCCLR** [SteffeyDev/atemOSC#213]
When I start ATEM OSC I get the attached error. I am unsure what to do as I have the ATEM software installed and working properly on my machine.
<img width="766" alt="Screen Shot 2021-04-14 at 7 52 26 PM" src="https://user-images.githubusercontent.com/82552238/114798571-4202da00-9d5b-11eb-8c57-79efcfce1090.png">

**Comment by SteffeyDev** [comment]
This is usually a version mismatch issue, which ATEM version are you running?

**Comment by SCCLR** [comment]
8.1.2

**Comment by SCCLR** [comment]
Updating now
