### ISSUE TITLE
Play Control on Hyperdeck

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#214]
I just realized that the Hyperdeck play command (hyperdeck/1/play) is now triggering "continuous play" rather than "single play," meaning it plays through all the clips loaded in the deck. PlayLoop does the same thing, loops all the clips, not just one. Continuous play is visible on the play button by a circle around the play icon. 

Now there is no way (I believe) to just play or loop a clip in "single play,."

Maybe I am missing something, but I believe there needs to be commands for both play modes, or is there already a way to do this? 

Thanks! 

Randall

**Comment by SteffeyDev** [comment]
I think you are looking for this:

Turn on/off single-clip playback mode on HyperDeck $i: /atem/hyperdeck/$i/single-clip <true|false>

**Comment by randallpacker** [comment]
Thanks Peter! I completely overlooked that command.
