### ISSUE TITLE
Full list of OSC-Addresses ?

### ISSUE THREAD

**Issue by JonathanHouser** [SteffeyDev/atemOSC#216]
Seems like the new version no longer has this tab under help. Am I missing something?

Jonathan-

**Comment by SteffeyDev** [comment]
Hi Jonathan,

Do you see the [ Connection | Addresses ] selector when you click on a switcher? You can click on the Addresses panel to look at the OSC addresses for that switcher.

![image](https://user-images.githubusercontent.com/10255587/115625972-d5438e80-a2ca-11eb-80c2-e91b6802b743.png)

**Comment by JonathanHouser** [comment]
AH! yes. Thank you

**Comment by JonathanHouser** [comment]
I did not see that. Thank you! Is there currently a way to assign DVE scale and location properties? To say a dial?

**Comment by JonathanHouser** [comment]
Awesome. I’ll do that! Thank you. Also is there a way to donate to the project? 

Jonathan-
