### ISSUE TITLE
Audio Gain control (ATEM mini)

### ISSUE THREAD

**Issue by JonathanHouser** [SteffeyDev/atemOSC#218]
I understand there is not currently fairlight support in atemOSC, but i'm not fully up to speed if the entire audio interface runs in failrlight or if just the more detailed EQ effects sections is fairlight. Anyways. I'm having a hard time adjusting the gain range. When entering the commands

/atem/audio/input/1/gain

I can control a from 0 - 1db but its limited in this range

I know this is operator error and most likely comes down to me not knowing how to input <float> variables but in the example 

 "/atem/audio/input/2/gain -30.0"

It no longer responds. What am i missing? do i need <> around the db range? 

Thank you!

Jonathan-

**Comment by randallpacker** [comment]
The db range is -60 to 0. That should give you the correct range you are looking for.

**Comment by JonathanHouser** [comment]
ok, cool. i think my issue is how do I actually reflect that range in the code? as in what is an example of how it should be written

"/atem/audio/input/2/gain -60 to 0"?

**Comment by randallpacker** [comment]
I am using VDMX to send OSC and this is how it is setup:

/atem/atem1/audio/input/5/gain
Float (normalized between 0 to 1.)
($VAL * 60.) - 61.

I hope that helps!!

**Comment by JonathanHouser** [comment]
Thank you for helping me with this. I guess what im asking for is literally what you are putting in the commands. like an example of how the code is precisely written. I'm super new at this so and exact example of what you would put into oscolator would be awesome. As in, no periods, or () that the computer cant read. Does that make sense. I'm and idiot and just cant figure out HOW to write the values

**Comment by JonathanHouser** [comment]
So I think I realize what im doing. in OSCulator I wasn't using the arguments box. figuring that out now. thank you!

**Comment by SteffeyDev** [comment]
Just to chime in, atemOSC does support Fairlight audio, which is why the gain commands work. OSCulator has a high learning curve, so if you are not familiar with it yet you may want to watch some YouTube videos to get up to speed. I haven't used it for a while. Glad you are figuring it out!

**Comment by SteffeyDev** [comment]
Also, check out #86. It is one of many issues where people discussed OSCulator, and #86 was audio specific.

**Comment by SteffeyDev** [comment]
Specifically this comment: https://github.com/SteffeyDev/atemOSC/issues/86#issuecomment-396033563

**Comment by JonathanHouser** [comment]
YES! Thank you!!
