### ISSUE TITLE
Feedback messages from rec/stop buttons

### ISSUE THREAD

**Issue by petrihiissa** [SteffeyDev/atemOSC#221]
Hi,

Would it be possible to get feedback messages from ATEM (Mini Pro) hardware recording (to external USB disk) buttons?

Now when pressing REC/STOP buttons AtemOSC Debug Message shows "[Debug] Switcher unknown event occurred: 1952672867" and no feedback messages are sent to OSCulator.

This would be really great to have, because it could be used to control "On Air" light that would turn on when recording is underway and turn off when recording is stopped (I'm not using ATEM hardware streamer but I always turn on recording before streaming session and turn off recording after streaming session, so this kind of "On Air" / "Recording Underway" light control would be very functional).

_Originally posted by @petrihiissa in https://github.com/SteffeyDev/atemOSC/issues/132#issuecomment-838785417_

**Comment by SteffeyDev** [comment]
After release, you will receive `/atem/recording/active` messages that contain a boolean value indicating whether the recording is active, when the recording is started or stopped, or when `send-status` is used.

**Comment by SteffeyDev** [comment]
Released in 4.2.0, feel free to re-open if you have any issues with this feature
