### ISSUE TITLE
Request: change T-Bar moving direction

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#226]
Hi there,
maybe this sounds a little strange in the first place, but is there any possibility to tell the atem to move the t-bar back in its origin position after it moved to eg. 50% ?
I´m stream a lot of concerts and overlay two cameras (slowly fade to 50%). Since manually moving the t-bar does not really look smooth, i use "auto" and then Osculator to stop the t-bar at 50%. But many times i want to go back to the first camera...
I tried to switch program and preview, but this is visible in the program out (ugly glitching....)
Can this be done with touchOSC at all (without a physical t-bar) or does anyone have an idea?
Cheers, Chris

**Comment by SteffeyDev** [comment]
Just getting around to these.  I may be able to add an endpoint that could do just this.  Next time I test, I'll test it out and see if I can make it work

**Comment by SteffeyDev** [comment]
Ok, after next release the `/atem/transition/bar/reset` parameter will be available to accomplish exactly this.

**Comment by SteffeyDev** [comment]
Released in 4.2.0, feel free to re-open if you have any issues with this feature
