### ISSUE TITLE
Feature Request: Feedback for Transition time

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#227]
hi,
can you give feedback of the transition time parameter? I want to show it as a number on my iPad since i control it with a midi slider without a scale....
thanks

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com/support would make it a higher priority for me.
