### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by offthegrid-mike** [SteffeyDev/atemOSC#228]
I am very fascinating about the functionalities of the atemOSC! 
I was looking for a way to develop an android application to control ATEM controller. May I ask if there is any way to use this module in android application?

Thanks!

**Comment by SteffeyDev** [comment]
Yep! Once you have atemOSC running on a computer that is on the same network as the switcher, you can use any Android app that sends OSC to control the switcher. A quick google search shows TouchOSC (https://play.google.com/store/apps/details?id=net.hexler.touchosc_a&hl=en_US&gl=US) works on Android, which I've used the iOS version of the app in the past to control switchers. I'm sure there's other apps as well.

**Comment by SteffeyDev** [comment]
If you are looking to develop the app yourself you just need to find an OSC Android library
