### ISSUE TITLE
DSK On Air Issue

### ISSUE THREAD

**Issue by joshjarmin** [SteffeyDev/atemOSC#229]
So I'm having an issue where I can turn off the DSK but can not figure out how to get it to turn back on.  What am I missing with this command?

It seems that both of these commands turn the DSK On Air button off:

/atem/dsk/1/on-air/0
/atem/dsk/1/on-air/1

Shouldn't 0 turn it off and 1 turn it back on?  I was able to get the /atem/dsk/1/on-air/toggle to work but I really need separate control over turning it on and off at different times rather than trying to figure out toggling back and forth.  Is there something I missing or doing wrong?  Thanks for the help!

**Comment by SteffeyDev** [comment]
Please read the documentation in the README. You should be passing true or false Boolean values to turn it on or off, instead of adding /0 and /1 to the address. The fact that it works in one direction is probably just an accident.

**Comment by joshjarmin** [comment]
Thanks for the response.  I have tried /atem/dsk/1/on-air/true and /atem/dsk/1/on-air/false but they do not seem to work.  Is that the correct syntax or is there a different way?

**Comment by joshjarmin** [comment]
I'm not sure how to "passing true or false Boolean values".  Sorry, I am rather new at this and still learning.  Any help would be greatly appreciated.  Thank you!

**Comment by SteffeyDev** [comment]
What tool are you using to send the OSC commands? Each tool has a different process for sending values

**Comment by joshjarmin** [comment]
I am using OSCulator and ATEMOSC with ProPresenter 7


Thanks,
Josh Jarmin
Director of Media and Tech

Mid-Way Baptist Church
<x-apple-data-detectors://1/0>6910 Fayetteville Rd.<x-apple-data-detectors://1/0>
Raleigh, NC 27603<x-apple-data-detectors://1/0>
919-772-5864<tel:919-772-5864>
Mid-Way.com<http://www.mid-way.com/>

________________________________

**Comment by SteffeyDev** [comment]
Ok, please review the OSCulator manual, specifically the section on OSC Routing Parameters. https://dl.osculator.net/doc/OSCulator+2.12+Manual.pdf#page9

The goal is to send a single Boolean argument to the address

**Comment by joshjarmin** [comment]
I have read through the manual and do not see how to accomplish this command.  Any advice you can give would be greatly appreciated.  Thank you!

**Comment by SteffeyDev** [comment]
Sorry I didn't respond, been busy with work.  Did you end up figuring this out?

**Comment by SteffeyDev** [comment]
If you look at the log in atemOSC, what does it say?

**Comment by jochemno** [comment]
I am having the exact same isue, using qlab to send to command.
this one works: /atem/dsk/1/on-air/auto
but these dont': 
/atem/dsk/1/on-air/false
/atem/dsk/1/on-air/true

What can i do to switch the key to off?

**Comment by jochemno** [comment]
ps this is the error:
[Error] Incorrect value type for /atem/dsk/1/on-air/false

**Comment by randallpacker** [comment]
You need to use 0 for off and 1 for on. Give that a try... 

/atem/dsk/1/on-air 0
/atem/dsk/1/on-air 1

**Comment by SteffeyDev** [comment]
We'll, more formally you should send true and false as I mentioned above...

/atem/dsk/1/on-air true
/atem/dsk/1/on-air false

But I think the issue @randallpacker is that they don't know how to set the value in OSCulator.

As far as I can tell, you just need to type `true` or `false` into the "Arguments" box in the OSC Route Editor dialog, which you used to enter the address. So Rewrite Address should be "/atem/dsk/1/on-air" and the Arguments should be "true" or "false" depending on what you want. If those arguments don't work, you can also use "0" and "1" integer values as @randallpacker mentioned, which are converted to true and false by atemOSC.

**Comment by jochemno** [comment]
thx guys for the quick reply, I will try this soon,(not in studio now) what I all ready know is that the 'true / false' option doesn't work.
Maybe it is the way Qlab sends the osc message

**Comment by SteffeyDev** [comment]
@jochemno it looks like you were sending the true/false as part of the address, instead of as an argument. If you are not already familiar, please research OSC message structure so that you can differentiate between the address and the arguments.

**Comment by jochemno** [comment]
after testing it looks like Qlab can't send the arguments the right way. I solved it with a /toggle command. That did the job.
so somehow the ...on-air/ false or 0 did not work at all. Atemosc responded that a wrong argument was sent.
So solved somehow...thanks for the help
