### ISSUE TITLE
Q: Latest atemOSC version compatible with SDK 7.5.2?

### ISSUE THREAD

**Issue by jeremiasmanninen** [SteffeyDev/atemOSC#230]
Hello there!

I have an original ATEM Television Studio and it can be safely upgraded only to firmware 7.5.2. The newest atemOSC versions that I tested a while ago does not work with it. I'm now using atemOSC version "2.5.6 (1)". Is there any newer version compatible with 7.5.2 firmware/SDK? Wanting to use the most recent one compatible to make sure I won't face any problems that are already fixed. :)

Best regards,
Jeremias

**Comment by SteffeyDev** [comment]
No, as a single volunteer developer I don't have the time to make releases backwards compatible with older versions.  I apologize for any inconvenience.  Let me know if you do face any problems.
