### ISSUE TITLE
Does not work when wifi is not connected

### ISSUE THREAD

**Issue by ThreeWayMedia** [SteffeyDev/atemOSC#232]
First of all our setup:

- Mac mini (M1, 2020) - Big Sur
- Fixed IP address 

When we are not connected to wifi or internet our atemOSC can't found our ATEM in the network, at this time it's also not possible to add a new switcher / device. We can always access the ATEM Control software and use the atem at this point. So he is in the network.

Once we connect to the internet (wifi) and we restart atemOSC we can see all the times we clicked on add switcher (full of empty switchers) and he is connecting to our current atem. 

Now we would like to tour with this machine so we will not have internet access all the time.

**Comment by SteffeyDev** [comment]
Thanks for reporting! I have a hunch why this might be happening, let me confirm by checking the code

**Comment by SteffeyDev** [comment]
I found a fixed, this will be resolved in the next release (which will hopefully be soon)

**Comment by SteffeyDev** [comment]
Released in 4.2.0, let me know if that doesn't fix it for you

**Comment by ThreeWayMedia** [comment]
Hi Peter,

Works like charm thanks!



Peter Steffey schreef op 2021-11-15 15:49:
