### ISSUE TITLE
No Response from Switcher

### ISSUE THREAD

**Issue by lucasjackmusic** [SteffeyDev/atemOSC#234]
I have a 2021 iMac running OS 11.6  
I am running atem osc ver. 4.1.4(1) 
I am running ATEM software control 8.6.2
I have an Atem mini extreme ISO
 
My switcher connects to my computer and atem software control flawlessly. It is connected with a USB-C cable. I do not use ethernet to connect switcher to my computer. 
 
AtemOSC, on the other hand, will not connect to the atem switcher. 

I have made sure the IP address of the switcher is entered correctly in the atemOSC software.  I have toyed around with different IP addresses but nothing works.  I repeatedly get the error message:
"No response from Switcher, retrying x more times"

Please assist.

**Comment by lucasjackmusic** [comment]
Firewall is disabled.

**Comment by lucasjackmusic** [comment]
I just updated my Atem Software Control to version 8.6.3. The same problem persists.

**Comment by randallpacker** [comment]
In terms of software control, your switcher is connected to your computer via ethernet. The usb-c connection is for video, not for atem software and atemOSC control. If your ATEM software is connected and controlling the switcher via Ethernet with the correct IP address, then atemOSC will work. Start by making sure the ATEM software has the correct IP number and can send commands to the switcher, and then the atemOSC will make the connection when you add a switcher profile. Once it does, refer to the second tab (Addresses) to obtain the correct OSC commands and test them with whatever OSC software you are using. Hope that helps.

**Comment by lucasjackmusic** [comment]
Currently my computer is connected to the atem with only usb-c. It works perfectly with Atem Software Control.   Are you saying that I need to also connect my computer to the atem with an Ethernet cable in order for AtemOSC to speak to my atem?

**Comment by randallpacker** [comment]
Yes, either your computer needs to be connected directly to the switcher via ethernet cable, or more commonly, to an ethernet hub or router that is connected to both the computer, the atem switcher and any other network devices. I suggest you refer to the Blackmagic atem manual for information about connecting networking your atem switcher. This is networking 101 that you need to fully understand before moving to the more advanced stage of atemOSC. It's important not to confuse video and network routing.

**Comment by trevorsargent** [comment]
@SteffeyDev any idea if it's expected that it would work over usb connection? [This Blog Post](http://blog.jackphelan.xyz/atem-mini-qlab-and-osc) seems to imply that it does...

**Comment by trevorsargent** [comment]
On further investigation it appears that the latest reverse of version 3 will discover my ATEM Mini when connected via usb, but version 4 will not.

**Comment by SteffeyDev** [comment]
No clue what affects this, I can do some tests and see.  Unfortunately, the networking is mostly out of my hands, but if there's an issue with the connection part of the more recent BlackMagic SDKs that I can reproduce, I can report it to the BlackMagic devs.

**Comment by dantepfer** [comment]
> Yes, either your computer needs to be connected directly to the switcher via ethernet cable, or more commonly, to an ethernet hub or router that is connected to both the computer, the atem switcher and any other network devices. I suggest you refer to the Blackmagic atem manual for information about connecting networking your atem switcher. This is networking 101 that you need to fully understand before moving to the more advanced stage of atemOSC. It's important not to confuse video and network routing.

You are simply wrong on this. The ATEM connects successfully to ATEM Software Control directly via USB, no ethernet required. And atemOSC 3.1.4 works fine this way as well, over USB only.

**Comment by SteffeyDev** [comment]
I've released a [new major version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0), please test on that and open a support request at www.atemosc.com/support if there are still connection issues.
