### ISSUE TITLE
USK TIE not receiving feedback

### ISSUE THREAD

**Issue by ales-michalek** [SteffeyDev/atemOSC#235]
Hello, 

I installed newest app to setup aux feedback. I noticed, that feedback on USK TIE stopped working, so my buttons won't light up. Can you please Help me? Thank you!

**Comment by SteffeyDev** [comment]
What log messages are you seeing? Is it sending the feedback but you aren't getting it, or is it not even sending?

**Comment by ales-michalek** [comment]
And DSK TIE works flawlessly. 
<img width="562" alt="Snímek obrazovky 2021-10-07 v 23 38 46" src="https://user-images.githubusercontent.com/60697319/136465930-4e413170-28ca-47a0-a4d9-da6d97351d23.png">

**Comment by SteffeyDev** [comment]
I found the issue, this will be fixed in the next release

**Comment by SteffeyDev** [comment]
Released in 4.2.0, let me know if that doesn't fix it for you

**Comment by ales-michalek** [comment]
Hello, 

Tank you for that fix. Looks like it works. 
ANd thanks a lot for all this Atem OSC app. It saves me tons of time and money!
