### ISSUE TITLE
Susbscribe to audio level meter

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#237]
Hi there,

do you think there is a possibility to get feedback for the audio level meter? If this is too much information maybe just only to get a feedback message if the input clips so you can have something like a red alert button to check audio levels :-)
or get a message everytime the peak level reaches a new level (but here you would need something like a reset button)

e.g. /atem/audio/input/$i/meter FLOAT

or only for clipping
e.g. /atem/audio/input/$i/clip TRUE/FALSE or 

or peak level
e.g. /atem/audio/input/$i/peak FLOAT

Cheers

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com/support would make it a higher priority for me.
