### ISSUE TITLE
Latest AtemOSC release that works with original BMD Television Studio with firmware 7.5.2?

### ISSUE THREAD

**Issue by jjmmfi** [SteffeyDev/atemOSC#238]
Hello everyone!

I wonder what would be the newest release compatible with Atem firmware 7.5.2 on the original BMD Television studio. I tested a few versions around a year ago and found that 2.5.6 was the one I got working. I chose it because BMD Swithers 8.1 was mentioned on 2.5.7 and because some 3.x.x versions won't work then for me. Anyone has gotten later versions of AtemOSC working with this configuration?

**Comment by SteffeyDev** [comment]
Hi @jjmmfi, I just released a [new major version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). It uses a different framework for connecting to switchers that claims that v7.2+ should still work, so feel free to give it a try and see!
