### ISSUE TITLE
Blackmagic VideoHub SDK support

### ISSUE THREAD

**Issue by klavito** [SteffeyDev/atemOSC#242]
Love to use atemOSC, but there is no options to send commands to videohub, please add them.

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com would make it a higher priority for me.
