### ISSUE TITLE
OSC addresses for Pattern parameters

### ISSUE THREAD

**Issue by reno-** [SteffeyDev/atemOSC#243]
Hi,
I'm trying to control pattern parameters such as size, symetry or softness, but I did not found the correct addresses.

Maybe someone could give me the correct address; or confirm that it does not work?

thanj you !

<img width="357" alt="Capture d’écran 2022-02-01 à 20 50 03" src="https://user-images.githubusercontent.com/127730/152040728-61708762-18d5-44e7-939f-1895242a9e0f.png">

**Comment by SteffeyDev** [comment]
I don't think I've added support for these parameters yet, so I'll mark this as an enhancement. Are the position parameters here distinct from the flying key position parameters? If not, you may be able to use `/atem/usk/1/fly/position-x`.

**Comment by reno-** [comment]
Ok, so I must wait for the next release. 

Thank you for your work !

**Comment by reno-** [comment]
Fixed  in 22803bd39872b5d80af2f07da5b33eb9f26f4053
