### ISSUE TITLE
OSC Parameters for USK Mask

### ISSUE THREAD

**Issue by reno-** [SteffeyDev/atemOSC#244]
Hi,
I'm trying to control the Mask parameters for USK, and it seems that the mask of the DSK can be controlled, but not the Upstream One.

Am I missing something?

thanks

**Comment by SteffeyDev** [comment]
What mode do you have the USK set in? Chroma? DVE?

**Comment by SteffeyDev** [comment]
Ah, I found the parameters you want.  Yes, atemOSC does not support that yet.

**Comment by SteffeyDev** [comment]
Fix in progress in #249
