### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jghankins** [SteffeyDev/atemOSC#252]
On 4.2.0 I'm observing a memory leak under macOS Big Sur 11.6.5

I have a Isadora test patch sending at 1hz freq a simple cut transition.  If you increase the cycle it increases the rate of memory leak.

I've not had time to open up in Xcode to find the source but it should be simple to recreate.   I've tested with both a ATEM Extreme and and ATEM 4ME broadcast.

I can attach the Isadora patch if required but it's just a OSC Multi Transmit Generator and a pulse generator with a command of
/atem/x/transition/cut where x is the ATEM name.

**Comment by jghankins** [comment]
Here's an Isadora Patch you can use to reliably reproduce.  
[cut-test.izz.zip](https://github.com/SteffeyDev/atemOSC/files/8311498/cut-test.izz.zip)
.

**Comment by SteffeyDev** [comment]
This should be fixed in [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0), as I completely rebuilt the app with a new tech stack. If you still have issues, you can open a support request at www.atemosc.com/support.
