### ISSUE TITLE
Is 4.3 Stable? 

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#256]
I just came across the problems with controlling the upstream Chroma on the Mini Extreme. I see there is a 4.3 release (I'm using 4.2) that includes the additional protocols, but I wanted to know if it's stable to use or if there is something more recent with the Chroma features included. 

I am on the verge of launching a major broadcasting project with atemOSC, so it's not a great time to be testing. 4.2 is rock solid except it is lacking the Chroma support for the Mini Extreme. 

Thanks!! Randall

**Comment by SteffeyDev** [comment]
4.3 is not a release, but a milestone (planned release) that contains all the things I intend to do for 4.3. I don't have that development work done yet, and it will probably be another month or so before I have time to get the development for this set of features done and tested.

**Comment by SteffeyDev** [comment]
As you can see on the README, some `chroma` parameters are already supported.  Which parameters are you looking for?

**Comment by randallpacker** [comment]
As you can see from the screenshot, the Chroma controls on the Mini Extreme are completely different than the ATEM HD:

<img width="296" alt="Screen Shot 2022-03-28 at 5 47 40 PM" src="https://user-images.githubusercontent.com/3989315/160492987-522c75d7-ecd4-4f6c-9ed9-b0ce67f51837.png">

I just purchased it recently and am still incorporating all the new functionality into my project. Some of these Mini features are on the 4.3 list, which is why I asked. 

And by the way, if you send it Chroma Hue, Lift, etc., which I did accidentally, atemOSC crashes. 

This is not an immediate rush, but glad you are on it. Thanks!!

**Comment by SteffeyDev** [comment]
Ok, can you open a new issue specifically to support chroma on that device? I would like to test myself to fix crash.
