### ISSUE TITLE
ATEM Extreme crashes with ATEM HD Chroma commands

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#257]
If you send the standard ATEM HD USK Chroma commands (Hue, Gain, Y Suppress, Lift) to an ATEM Mini Extreme it will crash, since the Extreme has differently defined parameters (foreground, background, key edge, etc.) Not that you would want to do this! However, I did it by accident before I realized how the Mini has restructured the Chroma key paramaters.

**Comment by SteffeyDev** [comment]
This should be fixed in [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0).
