### ISSUE TITLE
Port issue on atemOSC

### ISSUE THREAD

**Issue by c434techteam** [SteffeyDev/atemOSC#259]
I have had several occasions now where atemOSC stops responding to commands being sent to it from OSCulator. I noticed this first when I thought it was the version of the ATEM Software Control I was using, but it turned out that wasn't the case. When I first setup atemOSC, it was listening on the default port, 3333, and then stopped responding. On a whim, I changed the port to 5555 and it started working again. Yesterday, that port stopped working as well, but later came back when I disconnected atemOSC from the switcher and reconnected.

The scenario I'm using is I have this on a Mac Mini M1 with 16GB RAM, running ProPrenter 7, LightKey, ATEM Software Control, OSCulator and atemOSC. I'm successfully able to use ProPresenter to control Lightkey, using Midi, every time. I have periods where I can control the ATEM from ProPresenter 7 through OSCulator, but the breakdown comes with atemOSC and the port. OSCulator shows atemOSC using UDP and I read somewhere that UDP isn't as reliable as TCP, but I'm not sure if we can switch the configuration to use TCP.

The main thing is I would like the port being used to always be available, without having to disconnect and reconnect from the switcher. I'm not sure what is causing it to happen, but if anyone has any ideas to make it more reliable, I would greatly appreciate it.

**Comment by SteffeyDev** [comment]
Thanks for explaining the issue. It's tricky to debug these issues, so I'll probably leave this thread up to see if other users are experiencing this as well. I can say that the OSC protocol is built on UDP, so TCP isn't an option. However, even though UDP is less reliable, it won't just quit working for a time period. Less reliable for UDP means that it might drop some packets, but if you re-send a few times at least one of them will get through.

Does disconnect and reconnect always fix, even if the port stays the same? Does changing port always fix without disconnecting or reconnecting? Or is it more random than that?

**Comment by SteffeyDev** [comment]
atemOSC has logs in the bottom panel, feel free to attach those if they are relevant

**Comment by ezbutton** [comment]
Concerning port 3333, if you have software that uses OLA (Open Lighting Architecture), it may take UDP port 3333. I am running LightKey and it launches olad on 3333. So, I switched to using a different port and it works fine. You can run the below to see which UDP ports are in use:

lsof -Pn | grep UDP

**Comment by c434techteam** [comment]
I've had it happen on 5555 as well, but thanks for the command to check the ports. I was able to use it all Sunday using port 7777 and in this case I didn't have the ATEM Software Control launched. Not sure if that had anything to do with it or not, but I was under the impression that I needed to have it opened, but it appears you don't.

**Comment by SteffeyDev** [comment]
Yes, you don't need ATEM software control open, atemOSC and ATEM Software Control use the same underlying SDKs to communicate with the switcher and are not connected

**Comment by c434techteam** [comment]
I haven't had the issue in a while. I've left it configured on port 7777. I will close the this out.
