### ISSUE TITLE
atemOSC lost connection mid-event, lost all connected switchers 

### ISSUE THREAD

**Issue by STP-Rob** [SteffeyDev/atemOSC#260]
I recently had an issue with atemOSC losing connection to my ATEM switcher during an event. I had established connection with my switcher, and OSC commands were successfully being communicated to my switcher through atemOSC. I am not sure exactly when the issue occurred (I discovered it after the event -- my operator was able to take over my ATEM manually), but I discovered atemOSC lost connection to my Switcher, and had wiped all information for connected switchers in the left-hand window -- the only option I had was "Add Switcher". 

I have not been able to replicate this since. And upon quitting and restarting atemOSC the switcher information came back and was able to reconnect with my ATEM. I haven't been able to find an issue listed here that describes atemOSC wiping all connected switchers after successfully connecting to a switcher.

I'm running atemOSC 4.2.0, with ATEM Software Control 8.7. 
My computer is an iMac -- running macOS, version Monterey 12.2.1

**Comment by STP-Rob** [comment]
Thanks for following up and letting me know! I'll make sure to copy any logs for your reference if I have this happen again.

**Comment by c434techteam** [comment]
I wonder if this is related to the same thing as my issue #259 but it is hard to say for sure.

**Comment by SteffeyDev** [comment]
This should be fixed in [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0).
