### ISSUE TITLE
T-Bar command changing Input to start from before starting the transition.

### ISSUE THREAD

**Issue by c434techteam** [SteffeyDev/atemOSC#261]
Here is the setup that we have and I'm not sure which component may be the problem, but wanted to post it here to see if anyone has seen similar things happen.

Monoprice SRP12 midi controller
OSCulator
atemOSC

Not every time, but frequently, when we start the transition using the slider on the midi controller, it cuts to the preview, then transitions back to the original program out. The midi controller is sending the codes as a controller code and that can't be changed in its configuration. I've attached a screen shot from OSCulator to see what it is receiving. I don't have atemOSC's messages available because it only scrolls back so far, but I can recreate the issue next time I'm in front of the computer. You will see that we have OSCulator listening on midi/cc9/1 for the tbar control.
![image](https://user-images.githubusercontent.com/106853857/174790275-44013220-fc91-43ef-bae9-4b8c0d954a8f.png)

**Comment by randallpacker** [comment]
I think that the problem is the MIDI slider is getting out of sync with the ATEM software. I believe it might make sense to either ONLY use the controller, or ONLY use Auto, but not both.

**Comment by c434techteam** [comment]
Yeah, we either need to always use the slider and just do it faster or use the T-Bar another way, unless they are both in the same position. I wonder how the ATEM Broadcast Panels handle that, they are motorized, which is possible.

**Comment by randallpacker** [comment]
I use Max MSP to control atemOSC, and when I control the Tbar, I automate an "auto" style transition, thus keeping ATEM and OSC in sync. I would figure out a way to do that with the software you are using.

**Comment by ruebyi** [comment]
@randallpacker would you show us your solution? Wich software are you using?

**Comment by randallpacker** [comment]
I'll get to that on Monday. In the meantime, as I recall, the key thing is that the T-Bar and the OSC range between 0. 1. are always together. And the way to do that is to never move the T-bar manually, but always with OSC. Anyway, I clarify Monday.

**Comment by randallpacker** [comment]
I take that back, I am having the same problem. With manual control of the T-Bar, every once in awhile when you reach 0 or 1, it flips and reverses itself. On the other hand if you use Auto Transition, it never does this, but then you have no control over the bar. This seems like it might be a question for Blackmagic.

**Comment by SteffeyDev** [comment]
I've made some improvements on this front in [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it still proves to be an issue, please open a support request on www.atemosc.com/support.
