### ISSUE TITLE
ATEM OSC constant crash

### ISSUE THREAD

**Issue by Joellugo79** [SteffeyDev/atemOSC#263]
hey there...i have been using an Akai mpd218 as a midi controller for ATEM television studio for months, no issues...this past sunday...its stopped working...and then today the program went from being open seeing the switcher to not even staying open, to just crashing on every attempt. before hand...when using osculator with the same commands that I've had initially i could see the commands go through but the changes weren't happening on the switcher any longer...atem software and hardware panel are 8.1.1  again no issues till this past sunday 6/26/22 and now 6/29 it just keeps crashing...even after restarts......i appreciate any help..here is the crash log:
[atem osc crash report.pdf](https://github.com/SteffeyDev/atemOSC/files/9014234/atem.osc.crash.report.pdf)

**Comment by Joellugo79** [comment]
UPDATE! I was able to trash it and start over it and and what was missing was the switcher "nickname" all is good again.

**Comment by SteffeyDev** [comment]
Glad to hear it's fixed! The nickname isn't required, but if it fixed it then awesome! I do see several crashes from that time range, though unfortunately I can't see the details because I'm on the free tier for my crash tracking service.

**Comment by Joellugo79** [comment]
@SteffeyDev Hey Brother....so I'm back with the crash issue again, but this time it seems worse, i cannot even do what i did before, its just constantly cashing...i have no clue what's going on I'm attaching the crash report...any help is appreciated...

**Comment by Joellugo79** [comment]
[atemOSC_2023-02-28-182556_Reals-ATEM-MacBook-Pro.crash.pdf](https://github.com/SteffeyDev/atemOSC/files/10855643/atemOSC_2023-02-28-182556_Reals-ATEM-MacBook-Pro.crash.pdf)
