### ISSUE TITLE
add osc addresses

### ISSUE THREAD

**Issue by chappydboz** [SteffeyDev/atemOSC#264]
can you make osc endpoints for the size,symmetry, softness controls on UsK3?
see screenshot of panel section im referring to..

we also need a toggle for the macro looping button

thanks

<img width="315" alt="77908B06-38AA-4F87-8E89-268212D3C4ED" src="https://user-images.githubusercontent.com/867659/180314487-a8db5277-b9bd-483a-883f-5aed13d15c1a.png">

**Comment by SteffeyDev** [comment]
The USK endpoints are now available on [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0).
