### ISSUE TITLE
Feedback for DSK cut/fill sources

### ISSUE THREAD

**Issue by Christoph111** [SteffeyDev/atemOSC#267]
hi,
for upstream keyers there is already feedback, can you please add this also for downstream keyers 1 & 2 (atem extreme), perhaps more in bigger switchers....
this would be great to have! thanks!

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com would make it a higher priority for me.
