### ISSUE TITLE
USK On Air not working

### ISSUE THREAD

**Issue by bjm8** [SteffeyDev/atemOSC#271]
The following commands are not working:

/atem/usk/1/on-air 1
/atem/usk/1/on-air 0
/atem/me/1/usk/1/on-air 1
/atem/me/1/usk/1/on-air 0
/atem/me/1/usk/1/on-air/toggle

These tie commands do work however:
/atem/usk/1/tie 0
/atem/usk/1/tie 1

**Comment by randallpacker** [comment]
The usk commands are working for me on my Constellation HD Switcher, software control version 8.9 (latest). atemOSC version 4.2.

**Comment by bjm8** [comment]
Television Studio HD
8.9 ATEM Software
4.2 atemOSC

**Comment by randallpacker** [comment]
It must have something to do with the way you are formatting. 
This works for me in max msp: 
On: /atem/atem1/usk/1/on-air 1
Off: /atem/atem1/usk/1/on-air 0

**Comment by bjm8** [comment]
/atem/**atem1**/usk/1/on-air 1

**That's not in any documentation so I did not try that.** Will have to report back later.

**Comment by randallpacker** [comment]
Good luck, and by the way I am not the programmer, I'm an artist using atemOSC trying to help people out.

**Comment by SteffeyDev** [comment]
@bjm8 Multi-switcher support is documented [here](https://github.com/SteffeyDev/atemOSC#multi-switcher-support). If you only have one switcher connected, you don't have to specify the label of the switcher you want (for @randallpacker, `atem1` is what he chose to label his switcher).

As for you issues, can you please attach the logs produced while you are sending the commands? That should help explain why they aren't working.

**Comment by bjm8** [comment]
Found the issue looking at the log files. Just the on-air commands (using QLab FWIW) in my cue stack were patched to our projector and not to the switcher. So sorry about this and thank you!
