### ISSUE TITLE
FTB on/off?

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#272]
I would so love to use the FadeToBlack with OSC but it is near impossible to control. Of course it "works" just fine, but impossible to control because there is no on/off or true/false, just a toggle trigger. It would be so great if it could toggle with 1 and 0, so it could be predictable whether you are turning it on or turning it off. Is this possible? Or is the current functionality baked in. 

Many thanks. 

Randall

**Comment by SteffeyDev** [comment]
I could add a custom set endpoint to improve that, I'll mark this as a feature request

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for version 5
