### ISSUE TITLE
Scan network to find the ATEM

### ISSUE THREAD

**Issue by dcrone** [SteffeyDev/atemOSC#274]
Our IT department refuses to allocate statically assigned IP addresses, so our ATEM Mini Pro keeps changing addresses. It's a royal pain to figure out what address it has. It would be wonderful if atemOSC could scan the network to identify devices that exist on the network, using the same methodology that the ATEM setup app uses.

**Comment by SteffeyDev** [comment]
I've moved this to my new internal issue tracker for [version 5](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0). If it is still something you would like, buying a license for version 5 and submitting this as a support request on www.atemosc.com would make it a higher priority for me.
