### ISSUE TITLE
No answer from ATEM switcher

### ISSUE THREAD

**Issue by silasnewdawn** [SteffeyDev/atemOSC#275]
Hello! Help please!

I have Ableton Live sending MIDI notes to OSCulator and I can see the midi notes being received by OSCulator. OSCulator changes midi cues to OSC messages. 

Atem OSC is connected to my switcher in the same network but it ATEM software control never changes cameras or anything.

OSCulator, atem OSC and ATEM software control are in the same computer. Am I missing any setting here?

It looks like atem OSC is not receiving messages from OSCulator. thanks!!!!! @iamjohnbarker @danielbuechele @SteffeyDev 

Please check the video below.

https://drive.google.com/file/d/1GeLdIFWuavxYWdaFhMwQIeTVt_xIFoSh/view?usp=share_link

**Comment by SteffeyDev** [comment]
The main thing I'm looking for are the atemOSC logs, in the bottom panel. It looks like logs exist, so atemOSC has received something, but you never showed the current logs. Please restart atemOSC, send a message through, and then paste the logs here so we can see. Thanks!
