### ISSUE TITLE
State synchronisation failed during connection attempt

### ISSUE THREAD

**Issue by joshjarmin** [SteffeyDev/atemOSC#279]
I recently started getting this error message while trying to connect to my ATEM 2 M/E switcher.   It has been working great for years and then suddenly it won't connect at all.  Any ideas?

When trying to connect it says: "State synchronisation failed during connection attempt". It tries 5 times and then fails and stops.  What should I be looking for?  The IP of the switcher is correct, I have rebooted both devices and reinstalled atemOSC as well.  

Thank you!

**Comment by SteffeyDev** [comment]
Sorry for not responding sooner. I'm working on a new version of atemOSC that may fix this issue, hoping to release in the next few weeks. I'll let you know when it's released.

**Comment by SteffeyDev** [comment]
Is the switcher running the latest firmware?

**Comment by randallpacker** [comment]
Hi Peter, I am using 9.01 ATEM Software control. I see it is up to 9.1 so I will definitely upgrade. As far as the switchers go, they all are on 8.X, different for each one. I’ll look into getting everything up to date. 

 

Randall

 

From: Peter Steffey ***@***.***>
Reply-To: SteffeyDev/atemOSC ***@***.***>
Date: Thursday, September 7, 2023 at 2:40 PM
To: SteffeyDev/atemOSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [SteffeyDev/atemOSC] State synchronisation failed during connection attempt (Issue #279)

 

Is the switcher running the latest firmware?

**Comment by SteffeyDev** [comment]
@joshjarmin The [new version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0) is now available, please see if that fixes your issues.
