### ISSUE TITLE
ATEM Supersource

### ISSUE THREAD

**Issue by superjlounge** [SteffeyDev/atemOSC#280]
Would it be possible to control X, Y and Scale for each box within the super source?

**Comment by SteffeyDev** [comment]
Hi @superjlounge, I just [released a new version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0) of AtemOSC with a new licensing and support model. Please go to www.atemosc.com to download the new version, and submit a support request there if the features you are looking for are not available in the new version.
