### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by danielbuechele** [SteffeyDev/atemOSC#45]
As discussed in #44 we want to improve the UI.
Here is an idea what the menubar could look like.

<img width="199" alt="screen shot 2017-10-10 at 23 12 23" src="https://user-images.githubusercontent.com/685740/31413350-a823dab6-ae10-11e7-805f-f9a231961dfb.png">

**Comment by danielbuechele** [comment]
I started working on this, but I'll wait for @SteffeyDev to have the refactor finished.

**Comment by SteffeyDev** [comment]
@danielbuechele Have you found any time to work on this in the last few weeks?

**Comment by danielbuechele** [comment]
Sorry for the long wait. I just pushed my work. Can you review and test?
