### ISSUE TITLE
Firmware 7.3 (Bug fixes filter down)

### ISSUE THREAD

**Issue by Fredscape100** [SteffeyDev/atemOSC#90]
Hi, my apologies to begin... new to this. Can I please ask for help regarding getting it to work with a switcher using v7.3? I hope I am posting this in the correct area of GitHub

I have two Television Studios, a Television Studio and the new Television Studio HD. The older model will not update to firmware 7.4 hence why I am using 7.3.

I am unable to get the latest version of atemOSC 2.5.3 (1) to connect to the older Television Studio running version 7.3. I have noticed that the MacOS running on my MacBook Air is 10.12.6. I think this might be the issue?

If this is the case, is there an older version of atemOSC I can use?

Any help gratefully accepted, thanks for taking the time to read this

**Comment by JamesFrank2525** [comment]
Does it connect to the new television studio correctly?

**Comment by SteffeyDev** [comment]
You'll need to download the last version that supported 7.3, which is atemOSC 2.5.2.  Here is the link to the DMG: https://github.com/danielbuechele/atemOSC/releases/download/v2.5.2/atemOSC.dmg

You can always find older versions on the releases page

**Comment by Fredscape100** [comment]
Great thank you, I think my confusion was that the latest release on the webpage highlights it is for 7.2, rather than for 7.4? I will download 2.5.2 later today 👍

Re. the new Television Studio HD, have not had the opportunity as not here right now but will try when it returns.

One thing jumps out to me is that the latest 2.5.3 overcomes a few bugs. But for people running the 2.5.2 version as their Television Studio Switcher will only support firmware 7.3, will probably still be exposed to these bugs as they are unable to use the latest atemOSC?

Can I please ask if all the bug fixing will filter down to a 2.5.2 version to allow us with the older Television Studio Switcher to still have (important) bug fixes?

Think everyone involved has done a great job, love the software, thank you 😀👍

**Comment by SteffeyDev** [comment]
Unfortunately, as the only active developer on the project with access to a switcher regularly, I'm not sure if I can promise to trickle down bug fixes to older SDK versions.  If I can manage to stay on top of all of the bug fixes needed and then have time left over, I may consider it, but there is only so much time I can dedicate to this project.  The only thought I have is that maybe we can automate building against older versions, but that is something I would have to investigate further.

Per your first note, I don't believe the website has been updated recently, @danielbuechele can you look into that?

I'm glad you are enjoying the software, and I appreciate your feedback.

**Comment by Fredscape100** [comment]
Thank you, appreciate and understand your comments re. updating 👍

**Comment by Fredscape100** [comment]
Thank you Peter, appreciate and understand your comments re. updating.
