### ISSUE TITLE
Test send OSC button

### ISSUE THREAD

**Issue by jeffmann** [SteffeyDev/atemOSC#95]
Doing troubleshooting of ports, addresses, and connections, it would be great if there was ~~a button in the atemOSC interface~~ a feature that would send an OSC message to the outgoing port.

**Comment by jeffmann** [comment]
Sure, that would be fine. I was having connection problems (see the previous bug) and just wanted to initiate a send from atemOSC (eg. like send-status does) to see if somehow the outgoing port was working but the incoming not.

**Comment by SteffeyDev** [comment]
If you are connected to a switcher and have ATEM software control open, you can just press the preview and program buttons in ATEM software control, that always triggers a send from atemOSC

**Comment by SteffeyDev** [comment]
Also, when a switcher is connected, it always sends out `/atem/led/green 1.0` and `/atem/led/red 0.0`, so you can just disconnect and reconnect the switcher and listen for that.

**Comment by SteffeyDev** [comment]
Not saying a button doesn't have its place, but in the meantime those should help.

**Comment by jeffmann** [comment]
Yes, that's helpful, thanks!
