### ISSUE TITLE
ATEM OSC not connecting to switcher

### ISSUE THREAD

**Issue by Nannarb00** [SteffeyDev/atemOSC#96]
I just downloaded ATEM OSC and osculator after watching tutorials on how to get this setup to work. I immediately hit a brick wall when ATEM OSC would not connect to the switcher. Yes, I entered the correct IP address. The ATEM Software Control is able to connect without issues. I have changed the IP address of the switcher, removed network switches etc. Is there something I am missing?

**Comment by SteffeyDev** [comment]
If you go to the help menu in atemOSC, and then open the log, does it just keep saying trying to connect with switcher every few seconds?  Also, what version of atemOSC did you download, what firmware version is your switcher, and what macOS version is your computer?

**Comment by HARDKORE79** [comment]
hi!
i had the same problem.. working with : 
-macbook pro 2008 with OS 10.9.5 (the last version possible)
-atem OSC 2.5.4
OSCulator 2.13.3
connected to the atem with the green square icon
OSC addresses "need to be connected to show..."
log - Could not get IBMD Switcher AudioMixer Interface


or macbookpro 2012 with 
OSCULATOR 3.2.2
ATEMOSC 2.5.4

please help me, tnx!
Andrea

**Comment by Nannarb00** [comment]
My apologies for not posting an update. I reinstalled a newer version of ATEM OSC and it is working just fine. I am quite new to the Osculator/ATEM universe so I can't really help with troubleshooting. I just know that reinstalling both applications with newer versions solved it for me.

**Comment by HARDKORE79** [comment]
> My apologies for not posting an update. I reinstalled a newer version of ATEM OSC and it is working just fine. I am quite new to the Osculator/ATEM universe so I can't really help with troubleshooting. I just know that reinstalling both applications with newer versions solved it for me.

in macbook pro 2008 i have the latest version possible installed for OS 10.9.5
in macbook pro 2012 latest version from website

**Comment by Nannarb00** [comment]
Hmm. This isn’t quite the problem I was initially having because I couldn’t get the ATEM OSC application to connect to the switcher. If yours is connected, I don’t really know what to suggest. Maybe someone else on this thread has an idea?
